### ISSUE TITLE
🏁 Feedback v21.0.2

### ISSUE THREAD

**Issue by RobertCooperFerguson** [itchio/itch#1030]
Event log:

```
Error: net::ERR_CONNECTION_RESET
    at Error (native)
```

**Comment by fasterthanlime** [comment]
Did you close this because it worked on retry?

Did this happen during the 'setup' phase? (the "Installing dependencies" after the login form?)

Connection resets used to be a bigger source of problems before we switched to Chromium's network stack, but I suppose they can still happen — I just need to find a good way to test them locally so we can have some sort of retry logic!
