### ISSUE TITLE
Bug: Blank Grey Screen with JavaScript Shown on Launch

### ISSUE THREAD

**Issue by niedzielski** [itchio/itch#1040]
itch v21.0.4

I just upgraded my version of the Itch app (sorry, I don't know the previous version) on Ubuntu v16.10 and now when I launch I just get a big blank grey error screen:

![2016-12-04-00-55-21-827267751](https://cloud.githubusercontent.com/assets/1071806/20864844/5ba160a8-b9bc-11e6-813f-3cd8ed54fb69.png)

The output:

```
if (!window.isVisible()) { log(logger_1.opts, "Main window hidden, letting it close"); return; } if (!prefs.gotMinimizeNotification) { store.dispatch(actions.updatePreferences({ gotMinimizeNotification: true, })); const i18n = store.getState().i18n;
```

I tried pressing f12 and ctrl-s-i but neither brings up a debugger. When launched from the command line as `itch`, only the following output is printed:

```
Mounting crash reporter
Fully mounted crash reporter
[2016-12-04 @ 00:51:23.984] [itch] itch 21.0.4 on electron 1.4.8
```

None of the menu buttons seem to do anything except those that launch websites. The alt-tab program icon was also not set.

I closed and relaunched a few times and now it's fully working again. I'm not sure if this is a sporadic or one time upgrade issue.

**Comment by fasterthanlime** [comment]
Hmm, that code is part of [main-window](https://github.com/itchio/itch/blob/a40f93e275e97e186a6bde5bff0c250ece601538/appsrc/reactors/main-window.ts), no idea why it would be loaded as the window's src instead of interpreted though.

I'm hoping it's an electron but that will be found and fixed in further releases. I'd investigate more, but without a reliable way to reproduce it, it's probably best ot wait.

Thanks for reporting!

**Comment by niedzielski** [comment]
:+1: I'll reopen this guy if I see it again.
