### ISSUE TITLE
Gentoo Ebuild

### ISSUE THREAD

**Issue by Cogitri** [itchio/itch#1041]
Hello!
 
I just read https://itch.io/docs/itch/installing/linux/gentoo.html and as I'm using Gentoo I created an ebuild for it. It works flawlessly for me and it's pretty much based off of anders-lasson's discord [ebuilds](https://github.com/anders-larsson/gentoo-overlay/tree/master/x11-misc/discord) . As I don't write ebuilds often I'd appreciate feedback :)
It's not source based, but uses the pre-packaged tarballs instead (which isn't the gentoo way, I guess, but I don't want all those npm dependencies). I tested it on amd64, but it should work on i386 as well.
[Link to my repo](https://github.com/Keepco/gentoo-overlay-seadep/tree/master/x11-misc/itch)

**Comment by fasterthanlime** [comment]
Hey, thanks for contributing!

It's been a while since I used Gentoo, so I'm not much use reviewing the ebuild itself — perhaps other Gentoo users could?

I'm not sure how `make_desktop_entry` works, but I want to mention that we already have a script that generates a pretty complete `.desktop` file: https://github.com/itchio/itch/blob/7f5cab5e1fb1cb498d3b467c7dd36e6dbbd07d37/release/ci-generate-linux-extras.js

Is there a way that we could generate that ebuild on our CI and have it be easily accessible for Gentoo users? If I remember correctly, that would mean maintaining our own overlay?

**Comment by Cogitri** [comment]
Yeah, one would have to maintain a overlay, but it's pretty simple. e.g adding my repo to portage's repo directory:

Create a file with this content under /etc/portage/repos.conf/itch.conf with following content:
```
[seadep]

location   = /usr/local/overlay/seadep
sync-type  = git
sync-uri   = https://github.com/Keepco/gentoo-overlay-seadep.git
auto-sync  = yes
```

and create a directory
`[ ! -d /usr/local/overlay ] && mkdir -p /usr/local/overlay`

Afterwards one would have to issue emerge --sync and install itch afterwards. 

To maintain the overlay one just has to push the version number of the ebuild, as the ebuild uses that to determine which package to download. (e.g renaming itch-21.0.4.ebuild to itch-22.0.0.ebuild once it's released & testing it)

I will look into the script you mentioned, I just used make_desktop_entry, as that's the way it's documented in [Gentoo's developer manual](https://devmanual.gentoo.org/eclass-reference/eutils.eclass/). It creates a pretty bare `.desktop` file, but it's possible to append all the other options you want in the `desktop` file
It wouldn't generate a man page and an AppStream file though

Also: The script doesn't seem to work with Gentoo's current stable version of nodejs (4.6.1)

**Comment by noobpurple** [comment]
Actually, there's an ebuild up on the [unofficial portage overlays site](http://gpo.zugaina.org/games-util/itch), but its latest version is 23.4.0. Here's a link to their [ebuild](http://data.gpo.zugaina.org/hossie/games-util/itch/itch-23.4.0.ebuild). I'm gonna test it tonight and start incrementing the version number to see if it breaks.

  edit: I just realized this issue is from 2016, not 2017. Whoops! Years are difficult.
