### ISSUE TITLE
In library view - add go to store page button

### ISSUE THREAD

**Issue by zjalexander** [itchio/itch#1083]
I would love to have the ability to navigate to the store page from my library view. This helps when a download isn't running and I want to look into why, or i want to leave a rating, or want to look up background info on the game I'm about to play, or add it to a collection...

This is the view I'm talking about. It doesn't have to be a right-click context menu, the store page could also be one of the transparent icons like "install", "share", etc.  (For what its worth,  the shopping cart item is 'buy another copy' and it doesn't show up for every game). 
![image](https://cloud.githubusercontent.com/assets/6953993/21376137/7d6b97d4-c6e7-11e6-9fee-9e8e9ef9263b.png)

**Comment by fasterthanlime** [comment]
Have you tried clicking the thumbnail?

On Dec 21, 2016 04:10, "Zachary Alexander" <notifications@github.com> wrote:

I would love to have the ability to navigate to the store page from my
library view. This helps when a download isn't running and I want to look
into why, or i want to leave a rating, or just want to look up background
info on the game I'm about to play.

This is the view I'm talking about. It doesn't have to be a right-click
context menu, the store page could also be one of the transparent icons
like "install", "share", etc. (For what its worth, the shopping cart item
is 'buy another copy' and it doesn't show up for every game).
[image: image]
<https://cloud.githubusercontent.com/assets/6953993/21376137/7d6b97d4-c6e7-11e6-9fee-9e8e9ef9263b.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/itchio/itch/issues/1083>, or mute the thread

**Comment by zjalexander** [comment]
well, that's embarassing :)

**Comment by fasterthanlime** [comment]
Well, if it wasn't obvious for you it won't be obvious for some other folks - can you think of any UX changes we could make to make it obvious to everyone?
