### ISSUE TITLE
VC+ 2015 Redist Prerequisite does not install

### ISSUE THREAD

**Issue by EmptyKeys** [itchio/itch#1108]
So I followed docs and Sample Evil App and created manifest for my game. File is correctly in the root of the game and I'm using latest version of the app. I have Windows 10 with the latest updates.

[[actions]]
name = "play"
path = "CoG.exe"

[[prereqs]]
name = "vcredist-2015-x64"

I had to use normal ANSI, looks like UTF8 is not supported.
I uninstalled 2015 redist, rebooted and tried to start the game from the itch.io app.
It started without installing prereqs and ofc game start failed.

Any idea what's wrong?

**Comment by fasterthanlime** [comment]
> I had to use normal ANSI, looks like UTF8 is not supported.

What makes you say that?

> Any idea what's wrong?

Please give me a link to your game's page so I can check for myself :)

**Comment by EmptyKeys** [comment]
I created file in Visual Studio, by default it's UTF8 with Signature (few bytes on the start). Itch.io App failed to parse that with error message.

Game is here - https://emptykeys.itch.io/children-of-the-galaxy
Let me know if you need access. :p

**Comment by fasterthanlime** [comment]
> by default it's UTF8 with Signature (few bytes on the start)

Ah, so the BOM is the problem :) I don't really know why Windows tools insist on it

> I uninstalled 2015 redist, rebooted and tried to start the game from the itch.io app.

So, the app won't reinstall redists unless you nuke prereqs (or it's a fresh game install). You can do that with right click in the game's tab, "View details", click the "Nuke prereqs" button.

What I want to add next is detect that a game failed because of a missing DLL, then retry installing prerequisites - but currently, it only does it on first launch (on a fresh game install). After that, it remembers that it's done.

**Comment by EmptyKeys** [comment]
Yup, BOM is evil.

That worked. Super cool.

Detecting crash will be bit problematic tho. For example my game catches all crashes and logs them in files, then close the app. So unless we say that app has to return something on crash, you will never know.

**Comment by fasterthanlime** [comment]
> So unless we say that app has to return something on crash, you will never know.

Well, does it return a non-zero exit code at least? I could make it a dialog with a "Re-install prereqs & try again" button (with some better wording..)

**Comment by EmptyKeys** [comment]
I does not at this moment. I can make it so. :)
