### ISSUE TITLE
Linux Mint 17 has no repo entry, please add one.

### ISSUE THREAD

**Issue by RavenRohr** [itchio/itch#1113]
Codename for the distro is rafaela

**Comment by Deozaan** [comment]
What's the point of this?

Rafaela is Mint 17.2. There have been 3 new releases since then. The latest version is Mint 18.1. Why add only that old one?

You can see the other distro names here: https://linuxmint.com/download_all.php

Note that, except for LMDE (Linux Mint Debian Edition), Mint is based on the latest Ubuntu LTS, which is currently Xenial. So unless I'm missing something, there's probably no point in using Mint's codenames since they're pretty much covered with Ubuntu release names.

**Comment by fasterthanlime** [comment]
Well, since I'm not using Mint myself, I don't know what's best. Pull requests welcome for this I guess!
