### ISSUE TITLE
Esc/F11 should exit fullscreen

### ISSUE THREAD

**Issue by ubergonmx** [itchio/itch#1114]
Dear itch app team, although not shown in the documentation "User Guide", i would like to ask this simple stupid question, how do I exit the fullscreen? like there's no button to toggle fullscreen...

**Comment by fasterthanlime** [comment]
The only way to end up in fullscreen right now is for example, to watch a YouTube video and click the fullscreen button - for some reason it puts the whole app in fullscreen instead of just the player.

I think Esc/F11 are keys that people would instinctively try and should take the app out of fullscreen if it is (even though there's no key to enter fullscreen)

**Comment by ubergonmx** [comment]
I don't even know how i entered fullscreen though, Esc/F11 and Youtube exit fullscreen doesn't even work...
