### ISSUE TITLE
Animate GIFs only on hover (or user setting)

### ISSUE THREAD

**Issue by exelotl** [itchio/itch#118]
Hi! Excellent work on the launcher so far! I was able to download and play a handful of compatible games with no issues.

I've noticed that CPU usage is really high even when just displaying one animated gif.
Check this out:
![capture](https://cloud.githubusercontent.com/assets/569607/11804348/00410962-a2fb-11e5-9ae7-3a4e45873cfb.png)

The first cover image on the page is animated, and it causes the two itch threads to consume about 5-10% CPU each. I then went and added four more games with animated covers to the collection, and now the total CPU usage is around 20-30%

Hope it's possible to fix it, and not some fundamental issue with the rendering backend or whatever.

OS: Windows 7 64 bit
itch version: 0.9.3

Cheers, Gecko

**Comment by fasterthanlime** [comment]
I've noticed that too, but then again it's an issue I see with Google Chrome too :(

Maybe the API could return non-gifs if you've checked "never show me GIFs" in the user settings (ping @leafo). But afaict it's just CPU-intensive to display all those gifs :/

**Comment by fasterthanlime** [comment]
Wow okay this is now my #1 priority I think - app is SO MUCH SMOOTHER without gifs.

I'll just make them on-hover and use canvas to disable them otherwise.

**Comment by Deozaan** [comment]
I see that #685 was fixed in the latest version (17.6.6), supposedly because of this fix, but how exactly was this fixed? I still see animated GIFs in Itch even when I'm not hovering over them, and I see no option in Itch to disable animated GIFs.

That said, the CPU usage drops nicely (after several seconds) when Itch is minimized to tray.

I guess it just kills the tab? And that's why it has to reload it again when I restore Itch?

**Comment by fasterthanlime** [comment]
@Deozaan it's fixed in master, but not in any public 'release'. So it's not fixed in 17.6.6, no worries to be had.

**Comment by quyse** [comment]
@fasterthanlime Is it fixed in any version? Thumbnails are still always animated in v18.10.1.

BTW maybe animated thumbnails is not a good thing at all? Multiple people told me recently that when they saw itch.io in the first time, sparkling animation on the itch's front page made them close the page immediately and never be back again... Obviously they would never register to know that there's an option in settings to disable that. Animate-on-hover seems to be better default.

**Comment by fasterthanlime** [comment]
> Is it fixed in any version?

Yep, v18.10.1 definitely has the fix!

> Thumbnails are still always animated in v18.10.1.

You must be talking about web tabs (example: the "itch.io" tab), not native grid views (example: "Library" or when you open a collection).

> BTW maybe animated thumbnails is not a good thing at all?

The discussion always comes back, and I don't think there's any easy answer or fix (hover doesn't exist on mobile, for example). In fact, many people tell us that animations are what draws them to the site! I think this might be another case of emacs-vs-vim :)

**Comment by quyse** [comment]
> You must be talking about web tabs (example: the "itch.io" tab), not native grid views (example: "Library" or when you open a collection).

Oh, right, sorry. It works then.

> The discussion always comes back, and I don't think there's any easy answer or fix (hover doesn't exist on mobile, for example).

Ok, I see. Cannot please everyone I guess :)

**Comment by fasterthanlime** [comment]
> Cannot please everyone I guess :)

The main thing for me is this: if animations are enough to deter someone from ever look at a website again... what can we really do to address this? If we do make the images static, won't this kind of folks get stuck on equally simple things with the website? We're a small company, there's a bunch of stuff we haven't had a chance to fix yet - I can think of plenty of things to be unhappy about!

Even if we had a toggle directly on the front page that said "Stop animations" or something - would that be enough? Would these folks even see it / care enough to click on it? I'm wording this terribly but perhaps you see my point still?

**Comment by quyse** [comment]
@fasterthanlime Yeah I see your point, and I don't know, I'm not an expert in UX :) As I understand it's simply about first impression, like when you see a website and a giant nasty advertisement pops up, you will close the page without hesitation. So there're people who tend to think that animations/sounds/videos on web must not play aggressively (sorry for the word) unless it's the main content (like youtube). Also gifs may be more disturbing than videos because of low framerate.

I don't think a toggle on the front page will make much difference, probably nobody will notice it. If one wants to stop a video which started playing automatically (like on game pages on Steam), they know where to click (and also there's a checkbox nearby to stop autoplaying completely). With multiple gifs on a page, I wouldn't know where to click to stop them :)

On the other hand, we can look at existing stores. Steam doesn't show any animations on their front page except sliding banners of new games, and (auto-playing) video on a game's page. I remember I came to Gamejolt once and they had really nasty epilepsy-inducing gifs all over the place, but they changed that since then and now animate gifs only on mouse over.

So I don't know. It's sort of differentiating feature, and personally I got used to it, but I understand when people are complaining. Maybe it's possible to do some formal usability testing or leverage some analytics to understand how many people think like that? It probably correlates with age, profession and even country, like software developers may think that animations are "unprofessional" (at least it seems to be the trend in Russian community, specifically I was talking to a few Russian guys who are game developers).

UPDATE: apparently I'm wrong, and Gamejolt is displaying animated gifs again on their frontpage now.
