### ISSUE TITLE
notification area menu goes off screen at the bottom, making it mostly inaccessible

### ISSUE THREAD

**Issue by ohsix** [itchio/itch#1192]
as in title

and this is what it looks like
![itch](https://cloud.githubusercontent.com/assets/3180944/25074895/b1739eb6-22bb-11e7-9538-1da022d46fc2.png)

**Comment by fasterthanlime** [comment]
What's your window manager?

(I don't think electron exposes enough API surface for us to actually implement a workaround - window managers are usually in charge of placing window so that they don't go off screen. I did implement a fix for the main window on window, but the API for menu.popup is [pretty minimal] (https://github.com/electron/electron/blob/master/docs/api/menu.md#menupopupbrowserwindow-options) - there's nothing about directions, and we don't know the size of the popup menu in advance so we can't adjust x/y)

**Comment by ohsix** [comment]
gnome shell, and whatever it was seemed to have stopped, i think it is related to which version of libappindicator i have installed, checking that now ...


i checked, was probably a fluke/bug in libappindicator if anything

**Comment by fasterthanlime** [comment]
Ah, good to know, thanks! 🌟

**Comment by ohsix** [comment]
there was an update to the steam client on fedora (from rpm fusion)

* Wed Apr 19 2017 Simone Caronni <negativo17@gmail.com> - 1.0.0.54-9
- GTK 2/3 version of libdbusmenu at version 16.04.0 is required for a working
  tray menu depending on the desktop.

they added a fix for what i was seeing at the time with steam and itch (but again, it stopped happening)
