### ISSUE TITLE
Video players can make the app fullscreen, unclear how to go back

### ISSUE THREAD

**Issue by RenTec** [itchio/itch#1208]
Dear itch app team, I have figured out the cause to the app going full screen at times. The glitch is repeatable whenever a game features a trailer video or any other embedded YouTube video. When a user enters full screen on the embedded videos and closes the current web page tab, the itch app remains in full screen without a title bar.

[I had originally posted about this on the forums.](https://itch.io/t/73225/itch-app-fullscreen-bugfeature-#post-148595)

**Comment by fasterthanlime** [comment]
I'm not sure what the right behavior is here.

Playing a YouTube video then clicking its fullscreen button does switch the app to fullscreen. Clicking its fullscreen button again (or pressing "Esc" or "F11") takes the app off of fullscreen.

However, closing the tab does not take the app out of fullscreen. Should we do that? Or, should the webview be in *true fullscreen* when the app is fullscreen (hiding the sidebar & top of the app) so that it's obvious that the video is fullscreen & it needs to exit from fullscreen before doing anything else?

**Comment by RenTec** [comment]
Personally I think the app should exit fullscreen when a video player exits full screen to prevent any confusion and potential navigational bugs on users PC's. Alternatively being able to toggle the apps fullscreen state outside of video players would be an interesting option. As it stands with the video players ability to toggle the apps window state, video players once fullscreen only fill the app to the side bar be it a game play trailer from hovering over a game title in the store or watching an embedded YouTube video left in comments. Both of these modes make the app toggle it's window state so maybe changing the app to not go fullscreen if a video player isn't actually truly fullscreen or changing video players to actually take the entire screen when toggled.

**Comment by fasterthanlime** [comment]
> Personally I think the app should exit fullscreen when a video player exits full screen to prevent any confusion and potential navigational bugs on users PC's.

It already does - it doesn't when the player suddently disappears though (because the tab was closed).

> Alternatively being able to toggle the apps fullscreen state outside of video players would be an interesting option

You already can (by pressing "Esc" or "F11").

> changing the app to not go fullscreen if a video player isn't actually truly fullscreen

What's happening is that the player is in a `<webview>` tag - when it goes fullscreen, it takes all the room available in the webview, which is everything except the sidebar. So what I suggest above is to actually make the sidebar 0-width when a player goes fullscreen, so that the confusing event of "closing the tab containing the player but the app remains fullscreen" does not happen anymore.

However, even then, I think the tab could be closed, via Ctrl+W for example. So maybe closing a tab should always take the app out of fullscreen.

I'm also thinking of showing what Firefox & Chrome show when you go fullscreen: "Press [F11] to exit fullscreen". I'm sure they added it after feedback of users stuck in fullscreen - it's unclear that even a 4-second message will clear it up for everyone, though :)

**Comment by RenTec** [comment]
Yes I think a mini pop-up to notify users of window controls would fit
nicely. I like the idea of setting the side bar width to zero as well.

**Comment by fasterthanlime** [comment]
Merging with https://github.com/itchio/itch/issues/1203
