### ISSUE TITLE
Encourage future-proof formats for games on linux like Flatpak

### ISSUE THREAD

**Issue by jurf** [itchio/itch#1210]
Apart from that Flatpak offers other advantages like sandboxing, cross-distro compatibility, bundled deps (no more dependency hell, ever), etc., which I’m sure you’re familiar with.

I think Flatpak would also be useful for using as a backend to the Itch app, for several reasons, like painless delta updates, integration with the system, you get the idea.

Thanks.

**Comment by ghost** [comment]
I support this idea. Aside from ease of use for game and Itch devs, Flatpak's sandboxing is tremendous benefit to user security.

**Comment by mdeguzis** [comment]
I am starting to get into flatpak packaging. Is this packaged yet? I wonder if this isn't too bad to package.

**Comment by fasterthanlime** [comment]
We might be interested in supporting games packaged with Flatpak, but not in using it to distribute the app at the moment.

**Comment by jurf** [comment]
Yeah @mdeguzis NPM is probably the hardest thing to package with Flatpak.

**Comment by fasterthanlime** [comment]
> Yeah @mdeguzis NPM is probably the hardest thing to package with Flatpak.

Just a quick note: itch doesn't need npm (or node.js) to run. The [.tar.xz builds](https://github.com/itchio/itch/releases/tag/v23.6.1) here contain just native executables.

The reason the AUR package requires nodejs and npm is because it builds from source, because that's what ArchLinux package usually do.

In the future we're moving away from packaging the app directly as a .deb, .rpm, AUR package etc. and packaging https://github.com/itchio/itchSetup instead, which installs the actual app on first launch and is also used for self-updates.

I'm prepared for a barrage of "but it would be better if [...]" but it is better for us if we can ship new releases faster and in a consistent way on all three platforms, so that's what we're going for right now.

(itchSetup itself could be packaged using Flatpak, but I don't see a lot of benefits, since we wouldn't be using their update system, or their sandbox, etc.)

**Comment by fasterthanlime** [comment]
Closing in favor of #2074
