### ISSUE TITLE
Allow devs to upload special for-launcher builds

### ISSUE THREAD

**Issue by Enichan** [itchio/itch#122]
So Ultra Hat Dimension has a portable zip build and a non-portable executable installer which keeps the users data in 'Appdata\Roaming\Ultra Hat Dimension', and the app installs the portable zip build which I think is great! This does mean that the game's data (config, saves) are kept nested deep in the itch app's roaming data folder.

Ideally letting devs upload and tag a zip as 'this is the one the launcher should use and also don't show this as a download option' would allow me to create a non-portable version of the game for the itch launcher that keeps its data in 'Appdata\Roaming\Ultra Hat Dimension', which seems like it makes more sense.

**Comment by fasterthanlime** [comment]
@Enichan Save games etc. are definitely something we need to think about, esp. with game updates, but I don't feel good about duplicate builds.

How about this instead: the app could, when launching a game, pass a few environment variables. cf. #81 for instance, it could be `ITCH_DOWNLOAD_KEY`.

For this, it could pass `ITCH_SAVES_FOLDER`, and the only thing a game has to do is check if it's set, save there, and (ultimately) the app could even sync that to the itch.io cloud. If it's not set (someone's launching without the client) the game can just pick any location as usual.

**Comment by Enichan** [comment]
That could work. For UHD though, since the location of the game files is important re: documentation for custom maps, I wouldn't really want to support a third location users might find their files. In that case though I could check for either environment variable and just redirect to my own roaming folder?

**Comment by fasterthanlime** [comment]
> a third location users might find their files

Have you tried 0.9.3 ? There's an `open folder` icon next to the game's launch button on hover. Files are dead easy to find. (It sounds like you're talking about the game exe+data folder, not the saves folder)

**Comment by Enichan** [comment]
Oh, so there is. I downloaded before I went to bed, checked after I got up, you sure work fast! Yeah that works.

Anyway to elaborate on what particularly UHD does:
- It has a config file which also includes saves
- There's a 'Maps' subfolder with the game it checks for custom maps

Now the zip version just keeps these files with the game files. The setup however redirects this to %APPDATA%\Roaming\Ultra Hat Dimension (which also has a Maps folder) because if a user installs to Program Files everything falls apart. Now there's an easy way to open the game's data folder from within the launcher that fixes the problem somewhat, though the idea of a user's config, save, and Maps being nested so deeply inside another application's roaming folder kind of bugs me, if you get what I'm saying?

The saves folder could work, but then that's a 3rd location for users to put their custom maps, so I might still want to redirect to %APPDATA%\Roaming\Ultra Hat Dimension from within the game, which I could do by detecting those environment variables.

I'm not sure if that's something that's at all desirable though?

**Comment by fasterthanlime** [comment]
> being nested so deeply inside another application's roaming folder kind of bugs me, if you get what I'm saying?

Nope, I'm not sure I get it, sorry :(

The fact that it's currently `nested deep into itch's AppData folder` is just because that's the default install location (library if you will). Later, I'd like to add support for other install locations.

Custom maps and where to put them is an interesting question but it doesn't sound like the same feature to me (it looks more like a mod, and I haven't thought about that yet, as itch.io has 0 support for it currently)

For me, `game program` and `game user data` are two concepts clearly separated: everyone has exactly the same `game program`, but everyone has its own set of `user data`. `user data` is usually something light that can be easily sync'd to the cloud.

**In an ideal scenario where all the hypothetical features I'm talking about are implemented:** I wouldn't put mods / custom maps in `game user data` (because the overall size that can be eventually sync'd in the itch.io cloud will probably be limited per user per game).

Mods are something specific to.. installations, more than users, in my mind? I might want to have different mods on Windows & OSX for instance, with the same itch.io account.

**Comment by Enichan** [comment]
Ah, well if users can pick an install location then the whole point becomes moot because my problem with it goes away entirely. >_> In that case just keeping the maps with the install and optionally redirecting the save to a saves folder that is cloud synced would work fine.

**Comment by fasterthanlime** [comment]
> In that case just keeping the maps with the install and optionally redirecting the save to a saves folder that is cloud synced would work fine.

Perfect!

**Comment by fasterthanlime** [comment]
Closing in favor of #176 and #92
