### ISSUE TITLE
Have a per-game and over all "auto update library" setting

### ISSUE THREAD

**Issue by LiamDawe** [itchio/itch#1326]
Something that would be useful, especially say for people on slower or limited bandwidth connections (as well as preventing people auto-downloading broken versions) would be to have an overall setting to control if games are auto updated or not.

I would go a step further and additionally have a per-game setting too, that way people can have the choice. So if overall setting is on, they could turn it off for select games?

Thoughts?

**Comment by fasterthanlime** [comment]
> Something that would be useful, especially say for people on slower or limited bandwidth connections (as well as preventing people auto-downloading broken versions) would be to have an overall setting to control if games are auto updated or not.

You haven't visited the Preferences pane lately Liam have you

**Comment by fasterthanlime** [comment]
> I would go a step further and additionally have a per-game setting too, that way people can have the choice. So if overall setting is on, they could turn it off for select games?

That's actually a thing I want to ship soon - there's already a "Revert to version..." feature - but if you have automatic updates enabled (as opposed to checking "Ask me before updating" in Preferences) then within the next half-hour the game will be back to the most recent version again. So we need some way to pin individual games to a specific version.

It'll be easier to ship in v25 or right after v25 because individual game installs will get a proper dialog with various options (will also be useful for #366 #342).

**Comment by LiamDawe** [comment]
> You haven't visited the Preferences pane lately Liam have you

Doh.
> It'll be easier to ship in v25 or right after v25 because individual game installs will get a proper dialog with various options (will also be useful for #366 #342).

Great!

**Comment by fasterthanlime** [comment]
v25 did ship! And reverting to an older version of a game does pause updates for it. You can snap out of it by manually checking for updates *for this particular game*.
