### ISSUE TITLE
Feature suggestion: option to forbid uploads from installing via app

### ISSUE THREAD

**Issue by quyse** [itchio/itch#1336]
Our game's uploads are portable builds (state-of-the-art, folders pushed via butler, with .itch.toml and everything ;) ). However I'm thinking about adding additional uploads to the game, namely a .msi installer for Windows, and .deb files for Ubuntu's, assuming it's going to be easier for those non tech-savvy guys who doesn't use the itch app. But, then when someone tries to install our game via the app, the app is going to ask them what file to install, and it's not going to handle .msi and .deb files smoothly in case user chose them, is it? Of course uploads are to be named appropriately (like Portable/Installer/Ubuntu 16.04 .deb Package), but it's probably still hard to make the right choice for normal users of the app (they may not know that installer is bad for the app).

Maybe it would be nice to have an option for developer to prohibit certain uploads from being installed by the app?

**Comment by fasterthanlime** [comment]
> Our game's uploads are portable builds (state-of-the-art, folders pushed via butler, with .itch.toml and everything ;) )

:star: :star: :star: :star: :star: !

> Maybe it would be nice to have an option for developer to prohibit certain uploads from being installed by the app?

That's definitely something @granpc (and others) have brought up before

.deb and .rpm will just never get picked by the app, so those are no issue. Then there's .dmg and .msi, which the app knows how to handle - and there, it'll display a picker, because the .zip might be the soundtrack and the .msi might be the actual game (and you might want to pick which to download).

It's not a lot of trouble for us to add a "Prevent app from downloading" checkbox in the edit game page, but also, it would add even more cruft to the page, so I'm not sure what's the best solution.

What do you think @leafo ?

**Comment by fasterthanlime** [comment]
Moved to https://github.com/itchio/itch.io/issues/909
