### ISSUE TITLE
Purchases should be shown in order returned by API

### ISSUE THREAD

**Issue by leafo** [itchio/itch#1352]
Looks like they are sorted ascending

![2017-07-19_11-41-53](https://user-images.githubusercontent.com/15198/28383818-4b747f80-6c77-11e7-8871-3163661d3ac1.png)

**Comment by fasterthanlime** [comment]
Note that the `Library` tab is much more than just "my purchases".

So there's no really "API order" to map them to. I can definitely partially order by purchase date, but what about the games you don't have a download key for? (those that you've just installed - and which show up in Library too)

**Comment by leafo** [comment]
I assumed you the ones you've installed on top, that's fine. The relative orer of any thing you've bought should match what's returned by the api as a good starting point. The usecase I'm thinking of is someone just bought a game on the site and they would like to see to install when navigating to the library

**Comment by fasterthanlime** [comment]
> I assumed you the ones you've installed on top, that's fine.

What if you have like 20 games installed? The one you *just* purchased won't show up on top either

maybe a solution would be to sort by `installed_at or purchased_at` - so if you install something it bubbles on top, if you buy something else it'll still be further up

note that this is all moot if 1) the user has already scrolled down some (because tabs remember scroll positions) 2) they have another sort active (by name, etc.)

**Comment by fasterthanlime** [comment]
Alright, I came up with something I think goes in the spirit of that issue: https://gfycat.com/gifs/detail/sparserectangularbrahmancow
