### ISSUE TITLE
itch.io tab loads when opening a new tab

### ISSUE THREAD

**Issue by leafo** [itchio/itch#1356]
I open a new tab then navigate back to the itch.io screen. You can see on the sidebar there is a spinner on both. Additionally, the loading bar continues to go even though I've moved to a different screen. Lastly, when the loading completes the itch.io tab flashes, although I never told it to reload.

http://leafo.net/dump/browsertabs.mp4

**Comment by fasterthanlime** [comment]
Ah, I see what's happening. Since there's no way to prevent navigation, the way I keep the itch.io tab "frozen" is to open the newly-loaded URL in another tab and immediately "go back" in the itch.io tab - I supposed this acts as a refresh.

I'll look once again if there's a better way to do it in electron now, but afaict the only way is to inject javascript and that's always fragile :(

**Comment by fasterthanlime** [comment]
Alright, there's a semi-sane way to do it now, I'm on it.
