### ISSUE TITLE
Recognize signed InnoSetup 5.5.9 installers

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1389]
See #1277, test file: https://cosmoteer.net/downloads/Cosmoteer%200.12.2%20Setup.exe

**Comment by waltdestler** [comment]
Oh, you've linked the 0.12.2 installer, which is actually **not signed**. You can test with [this 0.12.9 installer](https://cosmoteer.net/downloads/Cosmoteer%200.12.9%20Setup.exe) which **is** signed. But if you've been testing with 0.12.2, then signing can't be a problem because that installer isn't signed.

**Comment by fasterthanlime** [comment]
I'll test both, thanks!
