### ISSUE TITLE
Blacklist .pkg files

### ISSUE THREAD

**Issue by retropipes** [itchio/itch#1426]
When itch downloads a .pkg file for Mac users, it treats the file as an archive and extracts it, thinking that installs the game; when, in fact, running the game fails with a "no executables found" error. To work around this issue, a user needs to go to the download folder for itch (simplest way to get there: hit show local files for the game in question, go up one level, then find the downloads folder in there) and manually double-click the .pkg to install it. This still leaves itch not knowing where the game actually installed itself to... but at least the user can play the game or use the tool this way.

I suggest .pkg files be treated much like .msi files are on Windows - don't extract them, instead launch with the appropriate native tool.

**Comment by fasterthanlime** [comment]
Here's the thing about .pkg files:

  1. They often require sudo (macOS just shows an 'enter your password' dialog)
  2. You can't pick where they're installed

The first is annoying already, since the app tries really hard to install a game without bothering you (so that, one day, you'll be able to just install N games from a collection with a single click).

The second one is a deal-breaker: the itch app should install games in your install locations, period.

MSI files have workarounds for both - a bunch of MSI packages are happy running without administrator privileges, and will respect the install folder you pass, which means they work just fine as a second-rate way to distribute games for the itch app.

However, I agree that "attempting to extract it then failing with no executables found" is bad behavior. The app should just straight up refuse to download `.pkg` files - just like it does `.deb`, `.rpm` for example.

Of course, we should also inform developers better so that they don't (at least not *only*) ship .pkg, .deb, and rpm files - there's a few ideas there: warn at upload time, notify the developer that an install of their game/tool was requested in app but their distribution format isn't compatible, etc.

**Comment by retropipes** [comment]
Yes, I agree. .pkg files are problematic for itch for the reasons you just stated. I'm fine with blacklisting them.

**Comment by fasterthanlime** [comment]
As it turns out, v25 was already blacklisting .pkg files, just added a test for it 🌟 

(I say 'was', but v25 isn't out yet)
