### ISSUE TITLE
🍎 Issue v23.4.2 -- Taking up soooo much space

### ISSUE THREAD

**Issue by droqen** [itchio/itch#1503]
Dear itch app team, 

I'm genuinely not sure if this is a bug or not, but here's what happened:

1. I started downloading Tacoma.

2. I realized Tacoma was 11 GB and immediately deleted it from the itch app. (I think I went to Downloads and clicked the 'Cancel Download' button.)

3. A few days later, my computer was out of space. Weird! I went hunting for the cause. Here's what I found:

<img width="445" alt="screen shot 2017-09-08 at 8 57 37 am" src="https://user-images.githubusercontent.com/5104632/30212701-13df700a-9474-11e7-8e87-5f2b26b0ed6c.png">

<img width="313" alt="screen shot 2017-09-08 at 8 59 43 am" src="https://user-images.githubusercontent.com/5104632/30212702-1577a20c-9474-11e7-9f9a-91bcc8d668a3.png">

The problems that I'm feeling are twofold.

a) Tacoma is taking up 7.55GB of space even though it's neither installed nor downloading according to the itch app! (I don't think I need to include another screenshot in order to show that it's not in my download list.) This tells me that not only is the itch app not deleting the files, it actually CONTINUED DOWNLOADING TACOMA despite my cancellation of the download. (My internet is not fast enough to get 7.55GB downloaded in the minute, or even seconds, that it took me to cancel the download.)

b) Secondarily I'm just very very curious/confused about why my 'downloads' folder is larger than my 'apps' folder, let alone this much bigger. Actually, I'll include a couple more images, of the current state of my downloads tab in the app:

<img width="234" alt="screen shot 2017-09-08 at 9 09 47 am" src="https://user-images.githubusercontent.com/5104632/30213095-88fb6eb0-9475-11e7-8e82-5794dcf06e9f.png">

<img width="818" alt="screen shot 2017-09-08 at 9 09 49 am" src="https://user-images.githubusercontent.com/5104632/30213098-8c243bbc-9475-11e7-8e4d-835f4adf8bd6.png">

So if I'm not downloading anything, what are all these anonymous .zip and .dmg files? Even if these files are for saving me on future patch downloads or something (butler?), it is a *hell* of a lot of space I wasn't really prepared to give up. I don't know if I can delete these files safely, but... I don't really care at this point...

I need that space.

**Comment by fasterthanlime** [comment]
Hey @droqen!

The good news is that a lot of work went into making this problem disappear in the next major release.

There's a bunch of reasons the app originally kept files in `downloads`:

  * For some installers (MSI), we needed the original .msi file to uninstall cleanly
    * While working on v25 I realized that Windows already copied any installed msi file somewhere, and you can just give it the package's UUID - so now v25 does that
  * When quitting the app in the middle of a download, and starting it up again later, it would resume downloading from the already-existing file

v23 removes the downloaded file when you uninstall a game (or cancel a download). However, it's buggy in that if you update a game several times then uninstall it, it'll only delete the last version.

---

TL:DR v23 is bad at cleaning up downloaded files, and you can safely clear out that folder.

v25 is much more conservative: it only keeps in the downloaded folder *what you're currently downloading*. It should handle pause on exit and resume when you start the app up again.

All the supported installer types (various archives like .zip/.7z/.rar, .dmg, .msi, various exe installers) can now be uninstalled without keeping around the original download, so there's no reason (anymore) to keep them around once the game is installed.

After upgrading to v25, the downloads folder will get cleared on launch.

---

Q: Why hasn't this been fixed earlier?
A: The vast majority of games installed with the app originally were in the 5-300MB range, and it was much less of a problem. They were small games that you'd install, play a few times and uninstall. So the original behavior was "acceptable".

Q: What happened since?
A: We released a bunch of tools (butler etc.) making it easier (possible at all, really) to upload much larger games to itch.io. We've been adapting the rest of the infrastructure along the way and the downloads folder issue is among the last.

Q: What's taking so long with v25?
A: It's a big cleanup, performance & reliability release. Paying off a bunch of technical debt accumulated while adding features to itch. It'll release with a 4-part postmortem explaining in detail "what took so long".

Q: So can I just obliterate the downloads folder whenever for now?
A: Yes, please do.

(As for the cancel download that didn't cancel, I'm going to look into now, that shouldn't happen even on v23).

**Comment by droqen** [comment]
Cool, thanks for the indepth response! I'm sure for even the majority of users the current setup isn't even problematic so I can understand it being low priority. I am on a laptop with not enough hard drive space and it's ALWAYS a problem so I'm often digging around to save space.

Is there any way I can help you with the cancel download that didn't cancel? I guess not, I've already deleted it... but maybe there's a log or something, I dunno.

~

Also, is there any way to tell from within the app if something uses butler or not, or, say, how big an update is going to be to download? That would be helpful. (Maybe just a 'save space and bandwidth' mode that always checks before pumping through a massive update... but nothing has that these days >_< it's becoming a shrinking concern ig)

**Comment by fasterthanlime** [comment]
> Cool, thanks for the indepth response! I'm sure for even the majority of users the current setup isn't even problematic so I can understand it being low priority. I am on a laptop with not enough hard drive space and it's ALWAYS a problem so I'm often digging around to save space.

It's one of these things that hit a low % of the userbase, but they get justifiably angered when they notice the current behavior, and the amount of work required isn't easy to justify considering how few users it hits - like I said though, the more big games we get on itch, the more % of users it's going to it, so it's been on my TODO list forever, it just happens to be "done" in master and planned for the next major release, so, good timing!

> Is there any way I can help you with the cancel download that didn't cancel? I guess not, I've already deleted it... but maybe there's a log or something, I dunno.

I don't think there's anything I need from you there - I *thought* the app deleted on cancel, but looking at v23's source, I can't find anything to that effect. v25 will definitely get it right.

> Also, is there any way to tell from within the app if something uses butler or not, or, say, how big an update is going to be to download? That would be helpful. (Maybe just a 'save space and bandwidth' mode that always checks before pumping through a massive update... but nothing has that these days >_< it's becoming a shrinking concern ig)

Seeing as I'm already working on some "treating disk space as a rare commodity" changes, this question isn't completely off-topic - the long-term plan is to give all uploads the "butler treatment" (including for upgrades), so they should how be "smaller". (In practice, we'll just run butler server-side to diff across two complete archives of the game uploaded).

---

As for seeing the size of things upfront, I have planned to have an intermediate dialog that shows you the size it'll take, lets you pick a non-default install location (instead of expecting you to do it in preferences beforehand, like it does now) etc. but I haven't figured out if it'd be better for it to be opt-in, or opt-out.

I'm guessing opt-out makes the most sense since we want new users to be aware of install locations etc., and it's mostly power users who care about "installing with the least amount of clicks possible".

In your case, since you care about upgrade sizes mostly, you'd want to also check "Ask me before updating anything", otherwise it'd still update in the background (without telling you how big it'd be).

Right now though, we have even more annoying issues - like the app not telling you upfront if you're going to run out of disk space while installing something. For butler-powered games, we actually *have* the data and could compute exactly how much space you need to install them, but for others (windows installers, .rar/.7z/.tar.gz archives) we need to add a phase to the backend

Also (since I'm doing in-depth posts right now), right now the app downloads the archive to disk *then* extracts, but the plan is to have it extract-while-downloading, which brings down the size requirements significantly.

Anyhoo, just wanted to reassure you that we're aware of these issues and it's generally moving in the right direction!

**Comment by fasterthanlime** [comment]
Hey @droqen! 

itch v25 shipped, and it's doing much much better at this.

First, it shows you how much space it'll need for a game before you install it:

![image](https://user-images.githubusercontent.com/7998310/45495399-7e20c900-b773-11e8-9031-d00c3a603d3f.png)

Second, the archive is never stored on disk (for. zip, .tar.gz, .tar.bz2, and any format supported by 7-zip.  Only installers and files from third-party servers are download to disk first), so if the game is 9.9GB and you have 10GB disk space, you can install it.

That means the downloads folder is no longer a problem:

![image](https://user-images.githubusercontent.com/7998310/45495555-bfb17400-b773-11e8-8928-9d2eb8055075.png)

...when you are actively installing or updating a game, it contains a few JSON and binary files storing download state, but that's it.

_Note that it won't automatically delete leftovers from itch v23 - feel free to nuke that folder one last time before installing itch v25_.

itch v25 is available now from https://itch.io/app
