### ISSUE TITLE
Installer butler extraction fails once (Windows 10, v23.6.0)

### ISSUE THREAD

**Issue by mostlytigerproof** [itchio/itch#1569]
Got this error running the installer. After I hit the retry button it completed successfully. I have plenty of disk space on that drive.

No anti virus other than Windows Defender. Real time protection was on. Nothing in the Event Viewer about it kicking in. Is there some place I should be looking for logs from the install?

Would also be nice if there was word wrap on the error text.

![capture](https://user-images.githubusercontent.com/9012872/32973234-3571e83c-cc5b-11e7-97bc-2f09151b0220.PNG)

**Comment by fasterthanlime** [comment]
I'd typically suspect an AV refusing to let us create (extract) an .exe file, but I've never seen Windows Defender alone do that. I'd also suspect a corrupted download but that particular codepath verifies SHA-1 and SHA-256 checksums before extracting so that seems unlikely too.

Unarchiver's error message isn't too enlightening either, so I doubt we'll figure it out until we can find a way to reproduce it.

At any rate, thanks for the report, we'll keep an eye out for similar reports!

**Comment by fasterthanlime** [comment]
Please re-open if you ever encounter this issue with itch v25 (which was released recently): https://itch.io/app
