### ISSUE TITLE
Installing butler feedback

### ISSUE THREAD

**Issue by mmpadget** [itchio/itch#1679]
Hello,

I found your instructions at: https://itch.io/docs/butler/installing.html mostly helpful, but pretty difficult to get working. I was able to figure it out with a _considerable_ amount of trial and error.

Note: the link "OSX 64-bit" downloads a file called "butler.dms", which does nothing. MacOS 10.13.3 (High Sierra) doesn't recognize the file type.

For Mac users I recommend making the following additions:

1. If the itch app is installed, butler can be run with the command:
`/Users/username/Library/Application\ Support/itch/bin/butler -V`

1. Create a .bashrc file in your home directory. Add the executable path:
`export PATH="$PATH:~/Library/Application Support/itch/bin"` (with no /butler on the end).

1. After creating or adding a path shortcut to .bashrc in your home directory you must restart bash with: `source ~/.bashrc`

1. These changes work for one session only. You can type `source ~/.bashrc` after startup to access butler.

1. You can automate the previous step by creating a `.bash_profile` file in your home directory containing `source ~/.bashrc`.

Best,
Michael

**Comment by fasterthanlime** [comment]
Hey, thanks for the feedback!

I feel like the primary pieces of information here are:

  * to add the `export PATH` directive to `~/.bash_profile` instead of `~/.bashrc` on macOS
  * to exit and start a new terminal to apply the path change (advanced users will know about the `source` trick)
  * to mention that the butler executable downloaded from https://itch.io/docs/butler/installing.html for Linux & macOS needs to be marked as executable first (via `chmod +x butler`)
  * that maybe it's clearer to list the folders rather than the executable path
