### ISSUE TITLE
Support pico8 games out of the box

### ISSUE THREAD

**Issue by ClementRivaille** [itchio/itch#170]
Game [Need For Seed: Undergrowth](http://rhythmlynx.itch.io/need-for-seed) is broken for me.
I get the same error in log for [The Wild Flower's Song](http://candleman.itch.io/the-wild-flowers-song) and [Project Sandtree](http://rikstar.itch.io/project-sandtree).

Here's the [debug log](https://gist.github.com/045c0d13f5f929dfe82c).

**Comment by fasterthanlime** [comment]
Ah, interesting, that's a pico8 game right? if only there was a way to separate 'regular pngs' from pico-8 cartridges.

**Comment by fasterthanlime** [comment]
So, the itch app is basically a browser — I'd be interested in letting itch users play pico-8 games, if [zep](https://twitter.com/lexaloffl) is okay with it.

I see the web player has a .js file — is there any documentation around it? I could sniff around but I'd much rather have zep's blessing / give time to figure out an official interface instead of setting up things that could potentially break.

In particular, I'd like
- To respect zep's branding wishes (logos, links, default format, etc.)
- A way to check for new version of and update the pico-8 player
- The ability to play games offline

Additionally, I'm curious if there's a good way to sniff if a particular .png file is a pico-8 cartridge or not. (Some games use the `.p8.png` extension but I prefer to rely on magic numbers / scanning for signature strings rather than trusting extensions.)

**Comment by fasterthanlime** [comment]
Probably blocked by #328 on this one — I'd feel better doing it in this order, at least

**Comment by fasterthanlime** [comment]
lexaloffle eventually responded to my messages, and it looks like this isn't going to happen. pico-8 1.0 is planned to have native exporters.

(note that web exports of pico-8 games will still play fine offline with the app, due to how it handles web games.)

**Comment by egordorichev** [comment]
Hi, I would just note, that adding web support for .png carts is super simple, and I think it's really worth doing it, it will save the creators tons of time :) Here is a tiny tiny library, that does it, but you can actually just extract the pico.js integration from it, that is just a few lines: [https://github.com/egordorichev/pico-player](https://github.com/egordorichev/pico-player).

I [run my cart gallery](https://rexcellentgames.com/carts/) on it, and it works great!
