### ISSUE TITLE
butler validate?

### ISSUE THREAD

**Issue by eigenbom** [itchio/itch#1744]
`butler validate` doesn't seem to exist anymore, as mentioned in [https://itch.io/docs/itch/integrating/manifest.html#validating-your-manifest](https://itch.io/docs/itch/integrating/manifest.html#validating-your-manifest)

> Before you push a build with your manifest file, you can validate with the butler validate command.

butler version: `v11.1.0, built on Feb 17 2018 @ 02:04:37, ref c8bcf300c4128c1d4cb0ca1cdc0a461c38f23a03`

**Comment by fasterthanlime** [comment]
It's in the bleeding-edge version (see `butler upgrade --head`).

I still have a few things to change before releasing a new stable butler.

I don't release those as often as I used to, because Antivirus software tend to dislike new binaries. We're in the process of setting up whitelisting for Avast and others.

**Comment by fasterthanlime** [comment]
butler v12.4.0 (stable) is out and ships with butler validate :)

**Comment by eigenbom** [comment]
Thx Amos <3
