### ISSUE TITLE
🏁 Issue v23.6.1 - Game not updating, stuck in "downloading updates"

### ISSUE THREAD

**Issue by dnielbloqg** [itchio/itch#1810]
Dear itch app team, 
despite de- and reinstalling the itch app several times, I am not able to receive updates for the itch app. It says "downloading updates" 
(in German),
![itch_2018-05-19_20-11-00](https://user-images.githubusercontent.com/34980975/40271684-d2a6d1c4-5ba0-11e8-9bd0-ac4c0865c04b.png)
and it stays like that. It works like 1 or 2 times after reinstalling it but after that said problem occurs again and again.
OS: Windows 10 Pro 64-bit

**Comment by fasterthanlime** [comment]
The good news is that we're changing self-update systems soon so this category of bug won't be an issue anymore

The bad news is that we're so close to shipping that I really don't want to dig into this right now.

You mention reinstalling several times but have you installed with the latest installer? https://itch.io/app is currently serving v23.6.3, yet this issue was apparently written from v23.6.1.

If you install v23.6.3 you definitely won't see that notification anymore. And there shouldn't be any more v23.x releases, so after that it won't be an issue :)

**Comment by dnielbloqg** [comment]
Thanks for the fast response.
I'll install the latest version and wait for the next updates.
