### ISSUE TITLE
install-kitch: Ship AUR package

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1918]

**Comment by bjorn** [comment]
Is this issue about fixing the [out of date kitch package](https://aur.archlinux.org/packages/kitch/) in AUR, which according to the [README in the kitch repo](https://github.com/itchio/kitch) is kept uptodate by CI?

**Comment by fasterthanlime** [comment]
Yes, it is.

Neither of the AUR packages (itch, kitch) have been updated for the v25 release, because it comes with its own installer.

I've started a discussion at https://aur.archlinux.org/packages/itch/ to figure out what to do about it.

**Comment by ghost** [comment]
I tried to build it because I assumed it was up to date today, so it's probably good idea to have it labelled as out-of-date.

**Comment by fasterthanlime** [comment]
> Neither of the AUR packages (itch, kitch) have been updated for the v25 release, because it comes with its own installer.

As of December 17th, 2018, this is no longer true! Both [kitch](https://aur.archlinux.org/packages/kitch/) and [itch](https://aur.archlinux.org/packages/itch/) now point to the latest version of the app (and will forever, since they actually install itch-setup).

**Comment by bjorn** [comment]
@fasterthanlime Nice work!

Btw, you can probably drop the `itch.install` entirely, since you [should not call `update-desktop-database` nor `gtk-update-icon-cache`](https://wiki.archlinux.org/index.php/GNOME_package_guidelines#GTK_icon_cache). `pacman` does this automatically using hooks.

(they should also be removed from the dependencies)
