### ISSUE TITLE
[win32] Broken game for v0.10.2

### ISSUE THREAD

**Issue by mthw** [itchio/itch#197]
Game [VIDdEO](http://duneworld.itch.io/viddeo) is broken for me.

Here's the [debug log](https://gist.github.com/610aa61438dcf01c0e69).

**Comment by fasterthanlime** [comment]
Hey, thanks for the report! :tada:

RAR files are not supported and never will be —here's why: http://itch.io/t/11918/rar-support-is-not-happening-repack-your-games

I suggest you contact the developer & link them to that page!

**Comment by mthw** [comment]
all i did was choose install from the itch app. i had already downloaded the game a week ago and tried installing the standalone file after the itch app version failed, and that worked fine.

**Comment by fasterthanlime** [comment]
> i had already downloaded the game a week ago and tried installing the standalone file

Absolutely, I'm sure the RAR archive the developer uploaded is valid and that you can extract it using non-free tools — but the itch app will not support RAR ever, because of licensing issues (as explained in the link above)

So, for this game to be playable with the itch app, the developers needs to reupload an archive using a non-proprietary format such as .zip or .7z
