### ISSUE TITLE
Emscripten: URL scheme "itch-cave" is not supported

### ISSUE THREAD

**Issue by acdimalev** [itchio/itch#2046]
Building and uploading the "hello world" example for Emscripten results in a web application that runs successfully on the itch.io website, but fails on the app.  Bringing up the developer tools (shift+f12) displays the following error:

```
itch-cave://game.itch/index.js:1560 Fetch API cannot load itch-cave://game.itch/index.wasm. URL scheme "itch-cave" is not supported.

getBinaryPromise @ itch-cave://game.itch/index.js:1560
```

The "hello world" example that I'm talking about.

http://kripken.github.io/emscripten-site/docs/getting_started/Tutorial.html#running-emscripten

**Comment by acdimalev** [comment]
Here's an example to play around with.

https://acdimalev.itch.io/itch-issue-2046?secret=RsopObwr08TqxBA4pYr370dn6Yc

**Comment by fasterthanlime** [comment]
So, the `itch-cave:` protocol is something the itch app uses internally to serve HTML5 games from disk so that they work even offline.

It behaves like an HTTPS protocol but it looks like Chromium's implementation of Fetch doesn't care.

The fix would be to:

  * Serve games over fake-HTTPS
  * With a custom domain (`game.itch` sounds reasonable)
  * Intercept all HTTPS request at chromium's level (possible with https://github.com/electron/electron/blob/master/docs/api/web-request.md )
  * Serve the game's contents
  * If the domain is anything else, just let Chromium do its thing.

**Comment by fasterthanlime** [comment]
The main problem with the webRequest thing (which I'm pretty sure we used to do) is that we can only specify a redirect. I'll have to see if that results in a non-200 status code. If not, this could be real easy!

**Comment by fasterthanlime** [comment]
Alright, `onBeforeRequest` doesn't help at all, since it redirects the first request, and then everything is served from `itch-cave:` again.

There's `interceptHttpProtocol` that's left, although I'm not sure we can redirect that to itch-cave easily.

**Comment by fasterthanlime** [comment]
The `interceptHttpProtocol` approach seems to work. The only remaining issue is that it's serving with the wrong mime-type.

**Comment by fasterthanlime** [comment]
> The interceptHttpProtocol approach seems to work. The only remaining issue is that it's serving with the wrong mime-type.

Actually, using `interceptHttpProtocol` opened a whole other can of worms. Turns out Fetch usage can be enabled by just calling `webFrame.registerURLSchemeAsPrivileged` in the inject script, and now your example works fine for me in v25 :) I'll push a new beta build.

(In case you weren't already testing from the beta: https://fasterthanlime.itch.io/install-kitch )

**Comment by fasterthanlime** [comment]
This just landed in v24.54.0

**Comment by acdimalev** [comment]
Checking out v24.54.0.  Is there a tarball version of kitch?

**Comment by fasterthanlime** [comment]
> Checking out v24.54.0. Is there a tarball version of kitch?

https://fasterthanlime.itch.io/kitch

**Comment by fasterthanlime** [comment]
Although I would recommend going through kitch-setup: https://fasterthanlime.itch.io/kitch-setup for proper testing.

**Comment by acdimalev** [comment]
I see.  The canary releases are source artifacts.  The amd64 Linux zip of kitch is working well for me-- and I see the Emscripten example running there completely as expected, awesome!

I assume kitch-setup is the kitch build of itch-setup.

https://github.com/itchio/itch-setup

That's segfaulting on me, but I wouldn't be terribly surprised if that has something to do with my laptop setup.  I'm running a glibc chroot install of Void Linux on a musl install of Void Linux with a bunch of LVM mounting nonsense (don't ask) and that's caused me trouble with installers in the past.  I'll do some testing on clean installations and see if it's reproducible / open up an issue over in the itch-setup repo if it is.

**Comment by fasterthanlime** [comment]
> I assume kitch-setup is the kitch build of itch-setup.

Yes!

> That's segfaulting on me, but I wouldn't be terribly surprised if that has something to do with my laptop setup. I'm running a glibc chroot install of Void Linux on a musl install of Void Linux with a bunch of LVM mounting nonsense (don't ask) and that's caused me trouble with installers in the past. I'll do some testing on clean installations and see if it's reproducible / open up an issue over in the itch-setup repo if it is.

So, you're the exact 0.1% of the userbase for which there *are* direct downloads of the itch app. I'd be interested in knowing why it segfaults though, so please do open any issue with details you might find..
