### ISSUE TITLE
itch-setup with Desktop on OneDrive

### ISSUE THREAD

**Issue by catdogwolf** [itchio/itch#2170]
Something went wrong

itch-setup, v1.12.0, built on Oct  9 2018 @ 05:16:52, ref f34425d2a0952ca593d92c50679619eb4da0ad87

mkdir C:\Users\Games\OneDrive\Desktop: The system cannot find the path specified.
while creating shortcut

This pops up every time I try to download the app. I have a windows 10. what should I do?

**Comment by fasterthanlime** [comment]
Hmmm that's a new one. Is your Desktop actually on OneDrive?

If you open a command-line prompt (Start menu, type "cmd", press enter), and type "echo %USERPROFILE%" then press enter, what does it show? (You can attach a screenshot, copy/pasting from the command-line is a bit hard).

I might have to add a workaround for this, but I won't be able to test that it works since I don't have OneDrive set up on any of my test computers.

Just to make sure, the path `C:\Users\Games\OneDrive\Desktop` does exist already, right?

**Comment by fasterthanlime** [comment]
I'm going to dive into this issue because I'm curious about it!

I've set up a fresh Windows 10 VM and a new OneDrive account to find out how it works exactly.

---

First off, I've confirmed a few things I suspected:

  * This doesn't affect all Windows 10 installs, you need OneDrive installed
  * Default OneDrive installs only sync the Documents and Pictures folders:

![image](https://user-images.githubusercontent.com/7998310/47256587-14d35a80-d483-11e8-82f8-23ea0cf7b3fd.png)

At this point, itch-setup still works, and your desktop is still in `C:\Users\user\Desktop`.

However, you can enable Desktop redirection by using "Protect your folders":

![image](https://user-images.githubusercontent.com/7998310/47256602-43513580-d483-11e8-9ac7-908260abe745.png)

The default settings for "Protect your folders" include Desktop.

![image](https://user-images.githubusercontent.com/7998310/47256604-4b10da00-d483-11e8-9cb4-356ebee93800.png)

(I find the wording particularly funny).

**Comment by fasterthanlime** [comment]
After enabling "Folder protection", the Desktop shows OneDrive sync indicators:

![image](https://user-images.githubusercontent.com/7998310/47256628-8b705800-d483-11e8-98ad-b3d984d818ce.png)

I had itch installed previously, at this point it still launches fine:

![image](https://user-images.githubusercontent.com/7998310/47256648-bce92380-d483-11e8-9574-799c75495221.png)

(But self-update probably won't be able to update the shortcut)

**Comment by fasterthanlime** [comment]
Uninstallation works fine too. Re-installing the app from scratch also seems to work for me?

I'm thoroughly confused now.

![image](https://user-images.githubusercontent.com/7998310/47256670-2c5f1300-d484-11e8-95c5-cbc84e1f72f7.png)

**Comment by fasterthanlime** [comment]
I tried a few more manipulations (renaming/deleting/recreating the Desktop folder, disabling/re-enabling Folder protection for Desktop), but I just can't get itch-setup to fail. Sorry @catdogwolf !

**Comment by fasterthanlime** [comment]
I tried pretty hard to reproduce this one, haven't had news in a while, so, closing!
