### ISSUE TITLE
🍎 With .dmg files, Itch tries to write non-existent receipt to a non-existent folder

### ISSUE THREAD

**Issue by aaronfranke** [itchio/itch#2173]
![receipt](https://user-images.githubusercontent.com/1646875/47264710-f2285c80-d4e9-11e8-9a70-f38d67abd06c.png)

Says "No receipt found" then "Writing receipt..."

Yes I know that OpenRA's Itch packaging is not very good right now, but I did notice this while doing tests on MacOS and this probably shouldn't happen.

Itch v25.3.0 Butler v14.14.0 Itch-setup v1.13.0 macOS 64-bit

**Comment by fasterthanlime** [comment]
Looking into this right now - it doesn't manage to extract the .dmg file successfully.

I thought I knew all flavors of DMG files ("uncompressed", "entries compressed with bz2", "whole image compressed with bz2", "apfs"), but this is another beast entirely...

7za 16.02 fails to list it:

![image](https://user-images.githubusercontent.com/7998310/47563981-c65f0980-d923-11e8-9c1d-6f58bee17e3d.png)

...well, it lists one "file", which is actually an ISO partition, and it doesn't give it a size, mode, or anything. Extracting it doesn't create any file.

7z however (the "full"/proprietary variant) manages to list it:

![image](https://user-images.githubusercontent.com/7998310/47564059-058d5a80-d924-11e8-83a2-edb6e2b03949.png)

...so it's an ISO 9660 disk image.. in a bzip2 stream... in a bzip2 stream? I give up, with that and APFS, we're going to have to fall back to hdiutil, as mentioned by @wrldwzrd89 in https://github.com/itchio/itch/issues/2112.

I'm not glad about it, because that means we lose the nice "no temporary directory" properties of 7-zip-extracting-from-the-network, but at least we won't run into these cases anymore...

**Comment by retropipes** [comment]
Completely agreed... it's frustrating when the bar changes on us, but at least the OS has a way to make sure we can at least proceed.

**Comment by fasterthanlime** [comment]
Update: I've started working on a tool to wrap hdiutil properly, and handle EULAs: https://github.com/itchio/damage

**Comment by fasterthanlime** [comment]
Forgot to comment here, but this works fine in v25.4.0 now.
