### ISSUE TITLE
🏁 Issue v23.6.1

### ISSUE THREAD

**Issue by take5tm** [itchio/itch#2176]
Dear itch app team,

i tried installing the v25 updater multiple times, from both the itch app and firefox, and it just reinstalls v23? help if u can. on win10 running on my toshibia qosmio laptop. thanks <3

**Comment by fasterthanlime** [comment]
So here's what should happen:

  * You got v23 sitting in `%LOCALAPPDATA%\itch\app-23.6.3`
  * The installer installs v25 in `%LOCALAPPDATA%\itch\app-25.3.0`
  * It writes `23.5.30` as the current version in `%LOCALAPPDATA%\itch\state.json`
  * It updates your Desktop (`%USERPROFILE%\Desktop\itch.lnk`) and Start Menu (can't remember the path off the top of my head) shortcuts to point to:
    * `C:\Users\amos\AppData\Local\itch\itch-setup.exe --prefer-launch --appname itch`
  * Launching that shortcut should now launch v25 - app-23.6.3 is still here but is ignored by itch-setup on launch because `state.json` does not point to it.

Did any of these go wrong?

As a last-ditch measure you can always wipe `%LOCALAPPDATA%\itch` and run the itch installer again. You *are* downloading it from https://itch.io/app right ?

**Comment by take5tm** [comment]
alright it works now!! thanks <3

**Comment by fasterthanlime** [comment]
> alright it works now!! thanks <3

Cool, thanks for the feedback!

Did you eventually figure out what the problem was?
