### ISSUE TITLE
butler installation instructions outdated?

### ISSUE THREAD

**Issue by bjorn** [itchio/itch#2204]
It seems the installation process of butler has changed since [the documentation](https://itch.io/docs/butler/installing.html) was written, in particular the "automation-friendly way". It says:

> If you want to get the latest stable, for example, you could curl or wget the following URL:
>
> https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
>
> You can substitute `linux-amd64` with any channel listed on broth.

and:

> If you downloaded butler to a directory (let's say `~/bin`), you first need to mark it as executable. From a terminal, run:
>
> `chmod +x ~/bin/butler`

But when I use `curl` or `wget` to get the above URL, I seem to get a zip-archive that you can't just mark as executable:

```bash
[bjorn@thor ~]$ wget -O butler https://broth.itch.ovh/butler/darwin-amd64/LATEST/archive/default 
...
[bjorn@thor ~]$ file butler 
butler: Zip archive data, at least v2.0 to extract
[bjorn@thor ~]$ unzip -l butler
Archive:  butler
  Length      Date    Time    Name
---------  ---------- -----   ----
  2276972  2018-11-07 17:24   7z.so
 23314320  2018-11-07 17:24   butler
   160152  2018-11-07 17:24   libc7zip.dylib
---------                     -------
 25751444                     3 files
[bjorn@thor ~]$ chmod +x butler 
[bjorn@thor ~]$ ./butler 
bash: ./butler: cannot execute binary file: Exec format error
```

Is this an intentional change? I guess it may not really be a problem since `zip` will most likely be available on common CI platforms, but then it would be good to mention something about this in the docs.

**Comment by bjorn** [comment]
Note that this may not have changed recently, since until today I was using `https://dl.itch.ovh/butler/linux-amd64/head/butler` and `https://dl.itch.ovh/butler/darwin-amd64/head/butler`, which I guess used to be mentioned somewhere and are still serving a direct binary. I was trying to use the stable instead of bleeding-edge because of a crash I ran into with [this build on macOS](https://travis-ci.org/bjorn/tiled/jobs/454585071#L2752-L2775):

```text
• For channel `macos-snapshot`: last build is 103715, downloading its signature
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x473fb88]
goroutine 1 [running]:
github.com/itchio/butler/cmd/push.Do(0xc00030c0c0, 0xc000034660, 0x24, 0x7ffeefbfeacc, 0x1e, 0x7ffeefbfeabc, 0xa, 0xf501d85e01000001, 0xc000312508, 0xf500000004cc2760)
	/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/cmd/push/push.go:233 +0x788
github.com/itchio/butler/cmd/push.do(0xc00030c0c0)
	/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/cmd/push/push.go:85 +0xf5
main.doMain(0xc0000c0010, 0x6, 0x6)
	/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/main.go:259 +0xc07
main.main()
	/Users/amos/builds/be101814/0/itchio/butler/src/github.com/itchio/butler/main.go:131 +0x62
Script failed with status 2
```

**Comment by fasterthanlime** [comment]
Well, a runtime in error in butler push certainly got me out of bed.

However, since it failed 9 hours ago but worked 15 hours ago (at the time of this writing), it looks like a temporary server issue instead. I'm not sure exactly sure what server response could've caused this (I just reread the code and it looks like error handling should be correct, ie. https://github.com/itchio/butler/issues/155 should be fixed) but I'm confident it's temporary.

I see you've fixed butler install + build just a few minutes ago, the docs do need to mention it's a zip, I'll get right on that.

**Comment by fasterthanlime** [comment]
> Note that this may not have changed recently, since until today I was using `https://dl.itch.ovh/butler/linux-amd64/head/butler` and `https://dl.itch.ovh/butler/darwin-amd64/head/butler`, which I guess used to be mentioned somewhere and are still serving a direct binary.

A few words about this: dl.itch.ovh is a GCS bucket with Cloudflare in front, and it was used up until itch v23 to distribute butler. The issues with this were:

  * Cloudflare tends to blacklist entire ranges of IP (certain countries, VPN users, tor users)
  * The bucket was in "multiple regions", but still US - occasionally users were seeing download rates around 10KiB/s, with no explanation.

As of v25, all dependencies are served via https://broth.itch.ovh/ (it has a web index, so you can browse that). It's a small Go app that makes API requests to itch.io, and each dependency is an itch.io page. butler is at https://fasterthanlime.itch.io/butler for example.

It is now served as a .zip because 1) that's the canonical format for all wharf builds (butler is pushed using butler!), and 2) it comes with 7-zip libraries, which we need to load dynamically for licensing reasons. Note that if you somehow misplace the 7-zip libraries when installing butler, it'll heal them as needed, see: https://github.com/itchio/boar/blob/954937a3bbc191385c7a165580af7be5059d6e5b/szextractor/deps.go#L38-L48

broth URLs redirect to signed download URLs directly from our CDN, which means no arbitrary user lockout, and acceptable download speeds for everyone - that does mean curl's `-L` flag is needed, as you found out.

I didn't know about curls's `-J` flag - I personally wouldn't rely on the zip file name staying exactly the same, I simply use `-O` in itch v25+'s deploy script, see: https://github.com/itchio/itch/blob/6bf7f2bb1383cdfe67525e55eb0e20a2cdeb5382/release/ci-deploy.js#L18-L24

**Comment by bjorn** [comment]
> Well, a runtime in error in butler push certainly got me out of bed.

Haha, I thought you'd like to see that part! Judging from the crashed line it seems either `uploader`, `newPatchRes` or `newPatchRes.File` was `nil`. I guess it was most likely `newPatchRes`, but I didn't look further into the code to see how this can happen.

> I personally wouldn't rely on the zip file name staying exactly the same

Yeah, I somewhat hesitated before I changed that, but I considered the script more readable like that. I guess I'll change it to force the file name to just `butler.zip` next time the build runs into problems. :-P

Thanks for the update!

**Comment by fasterthanlime** [comment]
> Haha, I thought you'd like to see that part! Judging from the crashed line it seems either `uploader`, `newPatchRes` or `newPatchRes.File` was `nil`. I guess it was most likely `newPatchRes`, but I didn't look further into the code to see how this can happen.

Yeah that's my guess as well, but errors are checked at every step afaict, so I don't know how it can end up with an invalid response and a nil error :(

> Thanks for the update!

You can review the docs change at https://github.com/itchio/butler/commit/ad27420d69e808250d99335ef62e2dd94fbab58a - do you find it clear enough? Would that have saved you some time when exploring this?

**Comment by bjorn** [comment]
> You can review the docs change at [itchio/butler@ad27420](https://github.com/itchio/butler/commit/ad27420d69e808250d99335ef62e2dd94fbab58a) - do you find it clear enough? Would that have saved you some time when exploring this?

Definitely, answered all questions!

The only thing that raised an eyebrow is the part where you're still setting +x on butler. I didn't run into executable flag issues on my system at home (but I use UnZip by Info-ZIP) and neither on Travis CI on Linux or macOS (don't know which unzip is used there). The wording "tends to" is vague.
