### ISSUE TITLE
Forget about random access on RAR files

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#2267]
See https://github.com/itchio/itch.io/issues/967

Just estimate 1.5x size of the RAR and force download to disk first. Sucks but... after spending some time on https://github.com/DrMcCoy/dmc_unrar/ it's become clear to me that listing RAR files remotely is a bad idea.

**Comment by DrMcCoy** [comment]
Hmm, I still think it would be possible to do it on-the-fly, or did you dig deeper and discovered another roadblock I missed and/or forgot about?

I mean, yes, you won't have any information about any of the files (except the ones you've already read) within the archive while decompressing. No names, no sizes, not even how many files there are.

The alternate decompression interface wouldn't even be difficult to write, just a bit messy to get it to play well with what's already in place. And the resume feature needs a bit of clear thinking, otherwise it's probably easy to get confused there.

The only major headache I see is solid files, where several files are within the same compressed "chunk", so you can't necessarily cleanly resume even on the file level. That's a bit icky, because on resume, you'll have to decompress stuff you're throwing again.

**Comment by DrMcCoy** [comment]
I.e. I guess what I'm asking: would there be still value in this being on my TODO list? Because I am still interested in trying this, even though I'm not sure when I'll have the time.

But if you think this would be writing new code you couldn't use in either case, I'll lower the priority I gave it in my mind :P

**Comment by fasterthanlime** [comment]
> I.e. I guess what I'm asking: would there be still value in this being on my TODO list? Because I am still interested in trying this, even though I'm not sure when I'll have the time.

Nope! Feel free to heartily cross it off your mental (or physical?) TODO list. May we both sleep better tonight.

**Comment by fasterthanlime** [comment]
> The only major headache I see is solid files, where several files are within the same compressed "chunk", so you can't necessarily cleanly resume even on the file level. That's a bit icky, because on resume, you'll have to decompress stuff you're throwing again.

Yeah exactly, that was the deal breaker for me. Ideally, I don't want *anyone* uploading .rars to itch - doing streaming rar decompression is a cool feat (and if you think it's cool too you should attempt it!) but I don't think I'm going to ship it in production because I either want:

  * Information about *the whole contents* of an archive *without reading all of it*, which formats like .zip and .7z give me, and then do streaming decompression
  * Or, to not bother at all and just download the file to disk first

I think the initial RAR files I used for testing might not have been "solid" (have "interleaved blocks", as I call them now.. even though it's a misnomer) and so the read/seek patterns I was seeing (I graphed those a few years back, for science!) seemed reasonable, but folks nowadays use a recent Winrar with all the options cranked up, and it seems it generates solid files.

For me, switching to dmc_unrar is a win because, well, it actually decompresses the files properly on all platforms! Previously, for a game like https://bullwaresoft.itch.io/magical-prisma, it decompressed fine on Windows, but on Linux it just recreated the file hierarchy with null bytes all over, which was no good.

So, thanks a ton! Now I just need to remember to update butler's licensing all over, although it (well, its binary builds) has/have been GPL for a while already, due to them using 7-zip via dynamic loading. That's clear to me now.

**Comment by DrMcCoy** [comment]
Okay! :)

Large files are still somewhat important for you, right? As in, there are games that come with RARs over 2GB and/or containing files over 2GB, and you'd like to have dmc_unrar handle them as well?

> but folks nowadays use a recent Winrar with all the options cranked up, and it seems it generates solid files

Recent (win)rar versions are pretty aggressive in what they try to get the best compression rate. That's also, I guess, why there are files around with the Itanium filter: it just throws all the stock filters at the file and keeps it if it produces something smaller out of pure coincidence.

**Comment by fasterthanlime** [comment]
> Large files are still somewhat important for you, right? As in, there are games that come with RARs over 2GB and/or containing files over 2GB, and you'd like to have dmc_unrar handle them as well?

I would! And I might dive into the code again at some point. It seems it's mostly unsightly OS wrappers that are needed at this point, which, unfortunately, I'm fairly good at...

> That's also, I guess, why there are files around with the Itanium filter: it just throws all the stock filters at the file and keeps it if it produces something smaller out of pure coincidence.

Yeah that wouldn't surprise me at all. Ah well. 🤷‍♂
