### ISSUE TITLE
"Manage Collections" link is in a very unintuitive location

### ISSUE THREAD

**Issue by bradenbest** [itchio/itch#2294]
Summary: 

* I upgraded to 25.x from 23.x
* I couldn't figure out how to remove an item from a collection
* I raised this issue as "Cannot remove games from collections"
* I went ahead and booted up itch on my linux machine to remove the item
* I used what I saw in 23.x to attempt to find the equivalent link in 25.x
* I found it in a non-intuitive place and changed the issue name.
* I rolled the three comments into this comment for brevity

**Comment by fasterthanlime** [comment]
@bradenbest I'll happily respond to your issues when they no longer clearly violate our [code of conduct](https://github.com/itchio/itch/blob/master/CODE_OF_CONDUCT.md).

In the meantime, this is no way to speak to anyone. (Note: that includes the screenshot's alt-text).

**Comment by bradenbest** [comment]
@fasterthanlime the alt-text was automatically generated from the file name. I didn't intend for that to be seen. I also went ahead and updated the title. Is that more acceptable?

**Comment by bradenbest** [comment]
@fasterthanlime the alt-text was automatically generated from the file name. I didn't know it would do that (nor that anyone would see it). Sorry about that. I changed the image alt text and the issue title. Does this resolve the perceived violation? I honestly don't know what else could be interpreted as disrespectful here.

I think there's been a misunderstanding. I should clarify that it was never my intent to insult anyone. I called the *design* stupid, but not any individual *person*. The aim was criticism ("this is bad and here's why it's bad"), not insult ("this is bad and you should feel bad"). Just because someone does something I perceive as stupid doesn't mean I perceive *said person* as stupid. I hope that intent shows through in the fact that I opted to explain exactly why I thought it was 'stupid'. In explaining why it's bad, I'm necessarily showing faith in the dev team's competence. After all, if I didn't think they were competent, what would be the point of including a screenshot and offering my perspective to show why it's bad? Maybe in your culture, that type of tone is interpreted differently, but I assure you I meant no disrespect.

**Comment by bradenbest** [comment]
Or maybe culture has nothing to do with it. I have aspergers. My ability to parse your feelings only goes so far, and it's a much larger cognitive load that you may realize. I tried to understand why you got offended, and elaborated on my best guess (which I was only really able to make because you pointed to the alt-text as an aside, which had the word "stupid"). I admit that I could have completely missed the mark on whatever it is you took offense about, and if that's the case, then I don't know what to tell you. 

"I'm sorry"? But should I really have to apologize for something I don't really have control over? Should I be forced to constantly guess at what made you angry and make constant edits to the issue, going back and forth for potentially weeks? Is that really a reasonable approach, or are you just being passive-aggressive because you assumed I was being disrespectful in earnest? Do you even plan to address this issue at all, or have you decided that I am the enemy and opted to permanently ignore this issue after leaving a "sick burn"? And why do we have to get along for you to fix a bug/design flaw anyway? What sense does that make? Why is "but do I like this person?" a factor in whether or not a bug gets fixed? What do relationships have to do with software quality? Why does the CoC say to act like you're in a professional setting when the devs are apparently willing to ignore issues for unprofessional reasons? Doesn't that seem hypocritical? Maybe it is *you* who shouldn't be so vague. I mean come on, a link to a document and no quotes? Where's the quote showing what rule was apparently violated? Where's the quote showing what I said that apparently violated said rule? And apparently you think this is "obvious" because you said "*clearly* violate our code of conduct". No, it's not obvious. You are being vague.

Like, again, you use the word "issues", plural. Is that a typo? Not likely: "issues", "they", "violate" instead of "issue", "it", "violates". So are you preemptively using it because you think I'll make similar issues in the future? Are you saying that the issue about the tabs somehow violates the code of conduct too? HOW? All I said was that it was a "massive downgrade in my opinion". **That's** offensive? What *can* I say? Do you see what I mean about the larger cognitive load? Your response raises more questions than answers. Your response doesn't make *sense*. There's too much room for interpretation. And the more I *attempt* to interpret it, the more I dislike you as a person because I get this extremely petty vibe off of it. I don't want to do that. I don't want to make assumptions about the character of someone I don't know.

**Comment by fasterthanlime** [comment]
First, re: the "Manage collections" link:

I'm not happy with it either. The plan is to enable editing collections (adding/removing items at least, reordering may come later) directly within the app. The "Manage collections" link (whether in v23 or v25) is a temporary workaround, which, again, I'm not very happy with. It involves navigating to an entirely different view, loading an entire web page, dealing with a completely different style of UI, etc.

To be clear, I'd like collections to be editable directly from that screen:

![image](https://user-images.githubusercontent.com/7998310/58039561-633cfa80-7b33-11e9-9560-d695c082131e.png)

This involves adding API support for it (partially done), adding the necessary tooling both in [butler](https://github.com/itchio/butler) and [itch](https://github.com/itchio/itch) itself, and designing and implementing the UI for it. Some other things have higher priority right now, although I look forward to finally getting around to it.

Knowing more about how you use collections day-to-day would help make sure that feature fits your needs.

---

Re: the issues with the issue itself.

> What do relationships have to do with software quality?

Everything, because it's people who build software. You can bring up the exact same underlying issue with aggressive and dismissive language, coming from a "position of authority", or with respectful, humble language, coming from a "position of learning" - and even though it's the exact same underlying issue, the effect will certainly not be the same.

> "I'm sorry"? But should I really have to apologize for something I don't really have control over?

It's not about controlling how one feels.  It's about controlling the language one uses when discussing software with other people. Everyone, no matter their culture, background, current life situation, etc., gets frustrated over software - sometimes, very much so. This part just happens. The part that you definitely can have control over is how you translate that into messages that will be read by other humans, with their own culture, background, current life situation, etc. (And that's the part the CoC rules over - not you, but your posts).

Here's some good advice I've seen over the years:

  * If you're too angry to write about something - set a reminder to do it later!
  * Write a first draft, then throw it away. Then write the real post. (This might take a few iterations depending on how angry you are).
  * If you're unsure whether a post comes off as offensive, having someone else read it over (if you can) is usually insightful.
  * Finally, if none of the above can be managed (if there's really absolutely no time to word the post better), including a preemptive apology is a good idea.

"Why bother doing all of this? Why should *I* have to do that?" - you brought it up yourself: "cognitive load" is one way to explain it. If everybody just dumps their raw thought onto the issue tracker, every person reading each comment has to deal with the language and the emotions they convey in their own manner. On the other hand, if, when posting, everyone makes the effort - once - to use language as described in the CoC, then it's readable by everyone.

I can't help but notice your messages are mostly focused on the "don'ts" of the CoC (and you asked me to quote it). I'd recommend focusing on the "dos" instead:

> Examples of behavior that contributes to creating a positive environment
include:
>
> * Using welcoming and inclusive language
> * Being respectful of differing viewpoints and experiences
> * Gracefully accepting constructive criticism
> * Focusing on what is best for the community
> * Showing empathy towards other community members

The objective here is not to avoid everything that's forbidden - the objective is to do one's best to contribute meaningfully.

In the case of that issue, the words "stupid" and "incongruous nonsense" are mainly what I took issue with. The follow-up messages bring up another issue though: expectations.

You detail a scenario in which I started a personal vendetta against you, first by giving you a "sick burn" and then purposefully ignoring you. The reality is much simpler: at 6:30 in the morning, I read both your reports. While they both made valid points, the language used was unacceptable. I posted a link to the CoC, then went on about my workday. This evening, I checked out the issue tracker again, and here I am replying.

An issue can go on for days, even weeks, without response, without being "ignored". That's not unprofessional. There's just a lot to do. Maintainers don't "owe" particularly fast responses, and the language you used certainly would discourage someone from replying as soon as possible.

Here's how both your issues could have been worded instead (this is just an example, not the "one right answer"):

> Hi, I've recently upgraded to v25, and I'm unable to find the "Manage collections" button that I used a lot in v23. Has it been removed? I see in-app collection edition [was previously requested](https://github.com/itchio/itch/issues/108), is that still in the works? It would work even better for me. Thanks!
> edit: Found it: (screenshot).

And:

> I used tabs a lot in v23. Are they gone for good in v25 or am I missing something?

It's not overly cheesy language, but it also keeps an open mind ("maybe I'm missing something") and manages not to insult someone's decisions.

Hope this helps!

**Comment by fasterthanlime** [comment]
Closed in favor of https://github.com/itchio/itch/issues/108

**Comment by bradenbest** [comment]
@fasterthanlime thank you for the detailed response and trying to understand where I'm coming from. I'll try to do that, but if I say something in the future that comes off as offensive/insulting, please understand that as an autistic, I have no filter, and I *do* have trouble expressing myself in a way that doesn't get misinterpreted as rude or mean-spirited. I often say that I'm opinionated to try to adjust people's expectations about me, but the truth is, I have a hard time with it--I always have. When in public, I don't talk much outside of small talk. And I don't have genuine conversations with people unless we're already well-acquainted, because I know at that point that what I say won't offend them.

I admit most of what I said was pre-emptive. For example, I wasn't saying that you were ignoring me or owed a fast response based on the elapsed time; that's just what I had interpreted from your response--that there was a possible subtext of "I would have responded, but I'm going to ignore you instead"--so I mentioned the possibility preemptively.

And yes, I do agree that the manage collections page is suboptimal in the first place and that they should be manageable from the collection view page. I just assumed that the manage collections page was an intentional design choice and that questioning that would be beating a dead horse. I'm glad that you guys are trying to get rid of it nonetheless. Collections as they're currently implemented are a pain to work with.
