### ISSUE TITLE
Tried to download Itch.io

### ISSUE THREAD

**Issue by Voltronicsmash** [itchio/itch#2310]
I tried to download itch.io and run it multiple times even after restarting my computer and I get this error message every time:

_**Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 07:29:17, ref 57838bc373361f2c8938336674247f869999e862

Get https://broth.itch.ovh/itch/windows-amd64/LATEST: x509: certificate has expired or is not yet valid
While performing GET request to https://broth.itch.ovh/itch/windows-amd64/LATEST
while getting latest version
Error during warm-up**_

**Comment by fasterthanlime** [comment]
Can you try again now?

**Comment by smm-h** [comment]
Same happened to me. Tried many times, even ran it as admin and still didn't work.

**Comment by fasterthanlime** [comment]
> Same happened to me. Tried many times, even ran it as admin and still didn't work.

Please open your own issue with 1) a description of what happened exactly 2) your version of Windows, 3) the exact error message.

Also, please *never run the installer as admin*. It doesn't need or want admin privileges.

This issue was for an expired certificate, which has been renewed since:

![image](https://user-images.githubusercontent.com/7998310/63030467-aac4ef80-beb2-11e9-9432-1adb784d1d1c.png)

so I'm closing this one.
