### ISSUE TITLE
Could not validate version 15.17.0 of butler

### ISSUE THREAD

**Issue by p1nk13** [itchio/itch#2313]
I'm trying to install the app, but it keeps giving me the error "Could not validate version 15.17.0 of butler"
here's a log image:
![itchy](https://user-images.githubusercontent.com/35823256/63305386-3ae8a780-c2ac-11e9-8431-4acc1c850245.PNG)
please help

Thanks,
p1nk13

**Comment by fasterthanlime** [comment]
Are you using third party antivirus software?

It looks like butler.exe was removed from the disk (maybe quarantined?)

**Comment by p1nk13** [comment]
I checked my quarantines, not there.
I made sure my antivirus didn't go after the app or anything else.

**Comment by fasterthanlime** [comment]
Then I'm not sure how that particular error could happen.

I'd recommend completely quitting the app (Ctrl+Q) and deleting the "broth"
directory altogether.

Everything should get restored on the next startup.

**Comment by p1nk13** [comment]
Didn't work

**Comment by fasterthanlime** [comment]
Is the exact same thing showing in the logs?

In `C:\Users\kelso\AppData\Roaming\itch\broth\butler\versions\15.17.0`, there should be three files:

![image](https://user-images.githubusercontent.com/7998310/63332714-6022f780-c338-11e9-9364-4adc1502ef76.png)

Are they all there? Does butler run? You can check via cmd.exe:

![image](https://user-images.githubusercontent.com/7998310/63332833-93fe1d00-c338-11e9-9ad1-b24434005a3d.png)

You could also try running https://fasterthanlime.itch.io/itch-diag - see if it reports any errors.

**Comment by p1nk13** [comment]
The files weren't there, so I tried adding butler manually, but when I tried to run the installer again it gave me the message again. Then I ran the diagnostics and it gave me this:
Running diagnostics (itch-diag v0.3.0)...

Collecting OS information...

Microsoft Windows 10 Home (64-bit), version 10.0.18362, build 18362

Installed 20190818010346.000000-300 — With languages {"en-US"} — Windows directory is at C:\WINDOWS

Collecting Security Center information...

Antivirus product: Windows Defender

Provides: Auto-update Settings, Antivirus

Unknown state (can't tell if running)

Definitions up-to-date

Verifying null service...

Verifying installed app information...

Install folder is E:\itch

Install state says current version is 25.4.0

Current version takes up 155.61 MiB in 117 files, 2 dirs, 0 symlinks

Diagnosing internet connectivity...

https://static.itch.io/ping.txt: HTTP 200 (in 567.9306ms)

https://itch.io/static/ping.txt: HTTP 200 (in 403.6231ms)

https://broth.itch.ovh: HTTP 200 (in 341.8288ms)

Diagnosing itch app dependencies...

broth packages: butler/

butler versions: 

While doing 'Diagnosing itch app dependencies': open C:\Users\kelso\AppData\Roaming\itch\broth\butler\.chosen-version: The system cannot find the file specified.
main.(*App).DiagnoseAppData
	C:/msys64/home/amos/Dev/itch-diag/appdata.go:57
main.(*App).Test
	C:/msys64/home/amos/Dev/itch-diag/main.go:161
main.(*App).Diagnose
	C:/msys64/home/amos/Dev/itch-diag/diagnose.go:30
main.main.func2
	C:/msys64/home/amos/Dev/itch-diag/main.go:49
runtime.goexit
	c:/go/src/runtime/asm_amd64.s:1337


All done!

**Comment by fasterthanlime** [comment]
> The files weren't there, so I tried adding butler manually

Cool, so everything makes sense. Now you just need to figure out what software on your computer is straight up yanking files off your disk.

(Dropping butler in there manually won't work unless you reproduce the right file structure - as you can see from itch-diag, it's missing `butler.chosen-version`). I'd recommend spending time finding the root cause rather than a workaround, because you're going to keep having that problem on every upgrade otherwise :(

**Comment by p1nk13** [comment]
I got it working, I'm using the latest kitch version. Edit: now I can't install games.

**Comment by fasterthanlime** [comment]
> Edit: now I can't install games.

I'm not overly surprised! .exe files seem to disappear all by themselves. I'm not sure the itch app can operate in those conditions :)

I'm sorry for the frustrating experience, but I *really* recommend finding out why the files disappear in the first place. If it turns out we can do anything about it, I'll happily ship a patch/fix/workaround in the app.

**Comment by p1nk13** [comment]
This the error that happens when I try to install games:
![Annotation 2019-08-20 141656](https://user-images.githubusercontent.com/35823256/63377256-5491f980-c355-11e9-8961-1c6e8c907a26.png)

**Comment by fasterthanlime** [comment]
> This the error that happens when I try to install games:

That's not the latest kitch. That's the latest release on https://github.com/itchio/kitch/releases. v24 is no longer supported.

The latest kitch can be installed with https://fasterthanlime.itch.io/install-kitch and it uses the exact same setup as stable itch, so you're going to have the exact same problems.

Of course, none of this matters because we still don't know why .exe files are disappearing from your computer :) Once we know that I'll be happy to help further! (For the latest itch stable version).

**Comment by leafo** [comment]
> I made sure my antivirus didn't go after the app or anything else.

It may be too late to help with this issue, but for anyone else who comes across this thread, please **turn off your virus scanner entirely** (temporarily), it can help us narrow down on the problem a lot faster.

This includes any other third party security or safety scanning tools (firewalls, etc.).

Thanks

**Comment by p1nk13** [comment]
> 
> 
> > I made sure my antivirus didn't go after the app or anything else.
> 
> It may be too late to help with this issue, but for anyone else who comes across this thread, please **turn off your virus scanner entirely** (temporarily), it can help us narrow down on the problem a lot faster.
> 
> This includes any other third party security or safety scanning tools (firewalls, etc.).
> 
> Thanks

It worked, but I made sure my antivirus (F-secure) didn't interfere. Why is that? Edit: had to do some fiddling around, I put the full path in my antivirus instead of %APPDATA%\itch\broth, turned on my antivirus, and now it works.
