### ISSUE TITLE
Add support for XDG Base Directories.

### ISSUE THREAD

**Issue by roket1428** [itchio/itch#2356]
For more info: https://wiki.archlinux.org/index.php/XDG_Base_Directory

**Comment by fasterthanlime** [comment]
There's been previous discussion about those, can you be more precise about what you mean by "support"?

**Comment by roket1428** [comment]
> There's been previous discussion about those, can you be more precise about what you mean by "support"?

I just quickly searched for "xdg" in issues section and couldn't find any so I created mine.
What I meant is getting rid of `~/.itch` directory and separate contents of `~/.itch` like cache things goes to `$XDG_CACHE_HOME`, config related things goes to `$XDG_CONFIG_HOME` and last but not least data related things goes to `XDG_DATA_HOME:-$HOME/.local/share` and their fallbacks as described in arch wiki.

**Comment by Jorengarenar** [comment]
Or at least simple environment variable (e.g. `ITCH_HOME`) would be enough, just to change the default `~/.itch` to something else

**Comment by fasterthanlime** [comment]
> Or at least simple environment variable (e.g. `ITCH_HOME`) would be enough, just to change the default `~/.itch` to something else

A while ago, I ran a survey on Linux users, to figure out if a majority would be happy with just moving "~/.itch" to something else (like `~/.local/share/itch`), and... that wasn't enough.

What @roket1428 suggested above is a *lot* of work - Electron has many different paths, changing them without breaking backwards compatibility involves moving/copying a lot of files on startup, conditionally, (and that check will have to remain for all future itch versions). I've already been bitten by Node.js being unreliable with file operations, so I don't want to ship that.

What makes this even harder is that both `itch-setup` and `itch` need to agree on paths - so the "transition code" would need to ship in both.

I guess what I'm saying is, this is a WONTFIX. I recommend symlinking `~/.itch` to somewhere else if you want - that shouldn't perturb either `itch-setup` nor `itch`, so you should be fine.

**Comment by Jorenar** [comment]
>I recommend symlinking ~/.itch to somewhere else if you want

The problem isn't `.itch` not being somewhere else, the problem is precisely the fact that `.itch` is in `$HOME` directory

**Comment by fasterthanlime** [comment]
I'm curious what the actual, day-to-day annoyance is here: if it was a storage space issue (ie. `~/.itch` is on a different partition than, say, `~/.local/share`, or `~/.config`), then a symlink would solve it.

The only problem I can imagine is a backup solution that:

  * Syncs up "~" to a cloud service
  * ...but already ignores `~/.local/share`, and `~/.cache` (or whatever the XDG environment variables say)
  * ...but isn't configurable enough to ignore `~/.itch`, and
  * itch is the only app installed that has its own dot directory

I'm having trouble imagining that in practice - and if it's not that, then what is it?

**Comment by Jorenar** [comment]
`$HOME` is a working directory with the start of shell. It's a directory from which one should navigate to other, more specific locations. It's a directory where most recent, most urgent, most used files should reside (e.g. TODO list).

When I type `cd` and then two times tab to show me the candidates (as on different machines I have different things, some are even shared with others) instead of just a list of important for me files/dirs + three XDG locations, I also get `.audacity-data`, `.bash_profile`, `.bashrc`, `.hplip`, `.itch`, `.mozilla`, `.profile`, `.ssh`, `.steam`, `.steampath`, `.steampid`, `.themes`, `.tor-browser` etc.

One could say "`~/.itch` is only one dir more, what the difference"? Well, it's not "only". It's exactly one more dir. If every program adds just "one dir", then in the end `$HOME` gets cluttered with dozens of them.

XDG Base Directory Specification, beside data separation, gathers all those dotfiles in better (and more importantly: configurable!) place, that's why every popular program gets request to obey it. It's really displeasing when in your `$HOME` (which, in my case, should contain 6 dirs, one file + three XDG locations) you get half a screen candidates to just `cd`

>A while ago, I ran a survey on Linux users, to figure out if a majority would be happy with just moving "~/.itch" to something else (like `~/.local/share/itch`), and... that wasn't enough.

In reality, env variable allowing to relocate it is enough to please most people. Maybe it isn't full, but it's better than nothing

**Comment by roket1428** [comment]
I think having an `ITCH_HOME` for now is fairly enough.

**Comment by merwok** [comment]
More about XDG Base Dir spec: it defines not ony a base dir (and envvar to override) for configs, but also one for state and one for cache.  This makes it easy to find (and backup) configs, leave program state alone, delete caches to save space.  The more programs follow that spec, the more value it has.

**Comment by roket1428** [comment]
> More about XDG Base Dir spec: it defines not ony a base dir (and envvar to override) for configs, but also one for state and one for cache. This makes it easy to find (and backup) configs, leave program state alone, delete caches to save space. The more programs follow that spec, the more value it has.

For a better example, you could have your caches on your ram to both speed up things and don't unnecessary harm your ssd.

**Comment by DanMan** [comment]
> A while ago, I ran a survey on Linux users, to figure out if a majority would be happy with just moving "~/.itch" to something else (like ~/.local/share/itch), and... that wasn't enough.

That's unfortunate, because anything is better than how it is now. Please? 🥺

**Comment by ghost** [comment]
> What @roket1428 suggested above is a lot of work - Electron has many different paths, changing them without breaking backwards compatibility involves moving/copying a lot of files on startup, conditionally, (and that check will have to remain for all future itch versions). I've already been bitten by Node.js being unreliable with file operations, so I don't want to ship that.

It's unnecessary for Itch to start moving files around itself. Simply support both paths, if `~/.itch` doesn't exist then write to XDG dirs. Existing users can migrate their files themselves if desired.

**Comment by Vinfall** [comment]
> What @roket1428 suggested above is a lot of work - Electron has many different paths, changing them without breaking backwards compatibility involves moving/copying a lot of files on startup, conditionally, (and that check will have to remain for all future itch versions). I've already been bitten by Node.js being unreliable with file operations, so I don't want to ship that.
> What makes this even harder is that both itch-setup and itch need to agree on paths - so the "transition code" would need to ship in both.
> I guess what I'm saying is, this is a WONTFIX. I recommend symlinking ~/.itch to somewhere else if you want - that shouldn't perturb either itch-setup nor itch, so you should be fine.

The symlink method is fine. And if you cannot stand a symlink being present when `ls` or `cd`, you can use `ls -la --ignore=.itch` and setup `FIGNORE` env variale by checking [this link](https://unix.stackexchange.com/questions/149912/exclude-particular-file-from-bash-completion) to pretend it doesn't exist (you can still access it anyway).

And I think the whole (missing) point of the issue is that ELECTRON is the one to blame, not itch.

If anyone wants this feature get implemented, try to [open a ticket on upstream Electron](https://github.com/electron/electron/issues/new?assignees=&labels=enhancement+%3Asparkles%3A&template=feature_request.yml&title=[Feature+Request]%3A+) or give an example (and open source) Electron app that respects XDG Base Directory Specification (I searched but could not find any😢. Is [xdg-basedir.patch](https://github.com/noahvogt/electron-xdg/blob/master/xdg-basedir.patch) relevant?), so it can really get off the ground.

**Comment by fenglengshun** [comment]
Currently, the main 'workaround' is probably using something like distrobox and making a container with --HOME set to (for me) $XDG_DATA_HOME/distrobox/arch. This way, `.itch` dir will be created at `~/.local/share/distrobox/arch/.itch`.

I personally would be fine if itch could be installed to `~/.local/bin`. I myself put native nwjs that I use to play some games by just putting them `~/.local/bin/nwjs-${pkgver}`, and then creating a script at `~/.local/bin/nw｀to run whatever current version of nwjs I'm running (I think symlink also works).

I think most distro should have a function on their bashrc to check and add `~/.local/bin` to `PATH`, though just in case maybe the installer could `mkdir` the folder and then detect if the directory is added the `PATH`, if it's not there it can manually add it to the `bashrc`. Normal people who uses app launchers/menus isn't an issue, just put in the .desktop file at `~/.local/share/applications` as usual.

Could also put it at `~/.local/share` and then do the same symlink/script to bin. Steam actually installs its containerized runtime at `~/.local/share` -- though it still creates a `.steam` symlink to that dir, annoyingly enough.

Alternatively, much like many apps, itch could install to `/opt/itch`. Electron apps should also work fine with that directory, `/opt` is where nwjs on aur installs to and it works fine. Same as above, make a script or symlink at `/usr/bin/itch` and create `.desktop` at `/usr/share/applications`.

I'm fine with whichever, so long as there is an option for it to not be at `~/.itch`.

**Comment by DanMan** [comment]
Why does that even still happen? I glanced at the code and couldn't find a hardcoded ".itch" directory. I did find the file [src/common/util/paths.ts](https://github.com/itchio/itch/blob/master/src/common/util/paths.ts) which seems to be where the paths are handled and they already use  https://www.electronjs.org/docs/latest/api/app#appgetpathname the right way, meaning it should already use the recommended XDG paths. Been that way in Itch since 2017 according to git blame.

There's even some reference to XDG in https://github.com/itchio/itch/blob/facf47b0d2e030b7cd704fb07a4fd75db2bf629a/src/main/reactors/open-at-login.ts#L25

So what gives? Has this been fixed by Electron?

**Comment by merwok** [comment]
That line you’re quoting is looking for autostart configuration, not the directory for config files.

The first link you give is more interesting: it shows that paths are computed with electron’s app.getPath function, which does follows XDG base dir spec!  https://www.electronjs.org/docs/latest/api/app#appgetpathname
So if the app is using these functions, then it should not create or use `~/.itch`.  It only needs to go a little bit further to separate config, app data and cache.

**Comment by DanMan** [comment]
Yeah, that's what I said. It seems like Electron changed its default path for config files on Linux to the one that XDG recommends. So maybe all that Itch needs is to update its Electron dependency? I dunno, hence my question.

**Comment by merwok** [comment]
Ah right.  I don’t know how to check docs for electron 11.5.

**Comment by jrom99** [comment]
I think the previous grievances are stale by now and the issue should be reopened or at least re-closed with a new explanation.

> > Or at least simple environment variable (e.g. `ITCH_HOME`) would be enough, just to change the default `~/.itch` to something else
> 
> A while ago, I ran a survey on Linux users, to figure out if a majority would be happy with just moving "~/.itch" to something else (like `~/.local/share/itch`), and... that wasn't enough.

The survey would be too outdated by now to even be relevant, but users here on the relevant issue have already provided their (more recent) feedback in support of this "hack".
 
> What @roket1428 suggested above is a _lot_ of work - Electron has many different paths, changing them without breaking backwards compatibility involves moving/copying a lot of files on startup, conditionally, (and that check will have to remain for all future itch versions). I've already been bitten by Node.js being unreliable with file operations, so I don't want to ship that.

Since this is already dealt with in the relevant tool (Electron), it should be more straight forward to update itch to respect the paths. I'm not really sure what you mean by "moving/copying a lot of files on startup" when this should preferably be done during install time, so one actually needs to check for the existence of relevant paths before any operations are done instead of hard-coding them.

> What makes this even harder is that both `itch-setup` and `itch` need to agree on paths - so the "transition code" would need to ship in both.

If they are related to this extent, then wouldn't it be better to have either `itch-setup` be a file in the `itch` repo or be a nested repository/submodule?

The current version of electron required is:

https://github.com/itchio/itch/blob/105041c6dabf596a5f3243c0c732326ee9102eaf/package.json#L112-L114

The docs mention support for it since at least eight years ago (v1.1.0):

https://github.com/electron/electron/blob/c40fb678903ee90730d5363e4e22d7d2738901e8/docs/api/app.md?plain=1#L273-L286

**Comment by DanMan** [comment]
It's dead simple, really: 

1. check if the new XDG path exists, if so, use it
2. if it doesn't, check if the original path exists, if so, keep using it
3. if neither exist, create the new XDG one, use it
4. have a variable somewhere that points to whatever path was determined (you surely already have that)

That's all I'm asking for. I'm not expecting any developer to clean up after themselves by moving files around. Any user who cares enough can just move the `.itch` folder into `.config` themselves.

There's zero risk for the developers in doing it that way. I don't get the apprehension that always comes up _at all_.

I personally don't care nearly as much about separating into config, data, … as I care about not having a dot folder right in my home dir.

**Comment by jrom99** [comment]
I'm actually really interested in itch having XDG support, but it's not really that simple:

* Itch doesn't use absolute paths AFAIK, and defers path handling to electron functions
* Itch doesn't differentiate between the multiple types (config, data, state, log) in their path handling
* The differentiation between state, data and config is not straightforward for most games (I'm not sure which game files itch actually handles, or if it just dumps their data in a "install location")
* Some games don't respect XDG anyway, for example those that use older versions of renpy
* Electron actually uses `XDG_CONFIG_HOME` instead of `XDG_DATA_HOME` for user data files and the dev understandably doesn't want the extra burden of setting SO specific paths when there was much trouble dealing with Node.js and electron

I can take a look later and link relevant code and issues for each point, but someone could make a PR anyway and see if the dev would be willing to check it.

**Comment by merwok** [comment]
Oh, I thought we were discussing where the itch client itself would store files.
For games, I would not expect many of them to follow good practices for paths, so I’d expect the itch client to sandbox each one with its own home directory (maybe also $TMP directory in an appropriate place) and let it create files freely there.

**Comment by jrom99** [comment]
> Oh, I thought we were discussing where the itch client itself would store files. For games, I would not expect many of them to follow good practices for paths, so I’d expect the itch client to sandbox each one with its own home directory (maybe also $TMP directory in an appropriate place) and let it create files freely there.

By default, itch stores the games' files in a folder inside `~/.itch`, or am I wrong? It's been some time since I changed my install location to `$XDG_DATA_HOME/itch/apps`

I'm not sure if the sandbox setting works the way you mentioned. I'm under the impression that it allows a game to do anything within its folder by default, and if unsandboxed write to other folders in the system. But it doesn't seem to make a game think that their folder is the `$HOME` directory.

There is also game data managed by itch that is not part of each game itself, such as metadata about version installed, available versions, scheduled updates, installation status...

**Comment by fenglengshun** [comment]
> Oh, I thought we were discussing where the itch client itself would store files.

This is also what I was thinking about it. I honestly don't care about the specifics. If Itch doesn't want to separate out what qualifies as config, cache, and data - I don't care, just lump everything that's in `~/.itch` before to `$XDG_DATA_HOME/itch` or something.

I just 1.) don't want to see `.itch` folder in my home; 2.) have simple directory that fits with my Linux backup scheme.
