### ISSUE TITLE
Recognizing What I Already Have

### ISSUE THREAD

**Issue by LukeVaxhacker** [itchio/itch#2369]
How do I get the app to recognize what I already have? I've moved 10GB+ of apps over the ~/Library/Application Support/itch/apps but nothing is recognized in a scan.

**Comment by fasterthanlime** [comment]
The scan is useful if you're copying over games previously installed with the app.

When the app installs a game, it writes a `.itch/receipt.json.gz` file that allows it to identify which game/upload/build it is, so that it can display the accurate metadata.

If the games were manually downloaded from the website, there's not currently a way to just "add them to the app" (it wouldn't know which actual itch.io game a folder maps to, nor which upload/build is installed, so it could never show upgrades, etc.).

So, as-is, the scan is useful when you copy games between computers, or restore a backup of games installed with the app.

Hope this helps!

**Comment by LukeVaxhacker** [comment]
When the scan finds a binary, the app could first search for the app name, then ask. That was closing too fast. Now a feature request.

**Comment by fasterthanlime** [comment]
I understand your frustration - I'm frustrated too! I've given this a lot of thought in the past (and now it's decided, hence the quick close) and there is just no good way to know not only the game, but also the exact upload and build, which is important for updates.

Similar functionality might arise as "Adding external games" functionality but it's unclear that that's something we want to do in the near future, so I don't want to get anyone's hopes up.

I'd suggest moving those manually-downloaded games to `~/Applications` instead and to just launch them with the Finder! (Ctrl+Space, or is it Cmd?)

Have a nice day!
