### ISSUE TITLE
Can't download the itch.io app

### ISSUE THREAD

**Issue by luckymasie** [itchio/itch#2430]
I keep getting this error:

Something went wrong

itch-setup, v1.18.0, built on Apr 10 2019 @ 06:29:17, ref 57838bc373361f2c8938336674247f869999e862

HTTP file not found on server
htfs.Open (initial request)
while opening remote signature file
Error during warm-up

**Comment by lunoche** [comment]
Me too

**Comment by rodjoost** [comment]
Same here, been trying all day.

**Comment by trickey445** [comment]
i also cant download it unfortunately, was going to get the bundle but idk anymore

**Comment by Abscissa** [comment]
Same here. This is why online installers are a bad idea.

**Comment by Xananax** [comment]
The bundle's success broke all expectations and is putting the servers under a lot of stress. It's good news, but unfortunately it means problems like that can happen. You can keep trying to download, or wait it out.

@Abscissa you can download the app at https://broth.itch.ovh/itch and unpack it to %LOCALAPPDATA%\itch (on Windows, not sure what the path is on Mac/Linux). Downloading manually won't be different than using the app, but you may feel more comfortable this way.

**Comment by rodjoost** [comment]
It finally worked for me after trying a lot of times.

**Comment by cgaspar** [comment]
@Xananax Unzip'ing manually doesn't work. It then fails trying to find butler. wget has no problem downloading the same base URLs that the installer fails on - the only difference is the tracking ID the installer uses. It seems the issue is in the data collection, not the download itself. Sad.

**Comment by fasterthanlime** [comment]
We've identified and addressed a bug in our backend, hopefully none of you should be having the problem anymore.

> It seems the issue is in the data collection, not the download itself. Sad.

This is absolutely not the case. The only purpose of the download session ID is to count each install as a single "download" operation, even though multiple files may be downloaded (a signature file, an archive file, some patch field, depending on what version you currently have). Note that download counts for the app and its dependencies are not linked to a user's identity.

The bug we identified was completely unrelated to that. It was an intermittent failure to serve downloads, which affected https://broth.itch.ovh - whether you used curl, your browser, or itch-setup didn't make any difference since the problem was server-side. That it worked the time you tried wget was a coincidence.
