### ISSUE TITLE
[linux] game War... broken for v0.11.3

### ISSUE THREAD

**Issue by ericlathrop** [itchio/itch#244]
:rotating_light: Game [War...](http://lapiroxx.itch.io/war) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/e1246daf21c3186c1853).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Looks like it was trying to launch a .so file. This has been fixed since — can you try upgrading to v0.12.4 and re-opening if you still encounter the issue? Thanks!

By the way, we have APT & YUM repositories that help linux users stay up to date, see here for instructions: https://github.com/leafo/itch.io/issues/300
