### ISSUE TITLE
Aseprite doesn't give correct downloads

### ISSUE THREAD

**Issue by LiamDawe** [itchio/itch#2471]
Aseprite https://dacap.itch.io/aseprite appears to only give Windows download options on Linux in the itch client.

I'm going to assume the [Wine detection](https://github.com/itchio/itch/issues/2462#issuecomment-655011036) stuff you mentioned you rolled out is not quite ready? 

Log file: https://gist.github.com/LiamDawe/75244a7234ce93271feb77dc3ecc49c0

**Comment by fasterthanlime** [comment]
Hey Liam,

Everything here is working as expected. Aseprite ships only `.deb` packages right now, and those are [filtered out on purpose](https://github.com/itchio/butler/blob/20e395f5d26f54c2414b39452f9be5e35e9ce427/manager/uploads.go#L100-L115) (see the [test for that](https://github.com/itchio/butler/blob/20e395f5d26f54c2414b39452f9be5e35e9ce427/manager/uploads_test.go#L24-L61)), because there's no way to install them without super-user access. Having the itch app randomly install .deb packages would be a security issue, besides, it would only work on deb-based distributions. That's a design decision.

If the "Wine detection stuff" didn't work, you wouldn't see any available downloads at all. It seems you're not the target audience for that feature - that's okay, a lot of other folks are happy to have the option to download and use Windows executables via Wine when the developer of a game/tool hasn't managed to navigate the complicated maze of "shipping for Linux" thoroughly enough for them.

Edit: I see there's a question in the Twitter thread that wasn't in that report: in v25, no, there is no way to download a file that the itch app doesn't know how to open. That's also a design decision, although it's one I changed in the upcoming v26. v26 will prioritize files it does know how to handle, but it'll still give you the option to download incompatible/unknown files.

Moving forward, can we agree to keep reports to "here's what I'm seeing / here's what I expected"? Blanket statements are not really helpful, and are certainly not the tone I'd like to encourage in the issue tracker.

Keep in mind there's a lot of constraints you might not be aware of - I understand your frustration, but assuming incompetence is not a great default to have when reporting bugs. I'm as frustrated as you, if not more - some things I can fix, and it takes time to do it right, and some things I cannot fix, and I have to live with that.

**Comment by LiamDawe** [comment]
I genuinely thought it was a mix-up with the Wine detection and wasn't at all aware of the app filtering out .deb files.

> It seems you're not the target audience for that feature - that's okay, a lot of other folks are happy to have the option to download and use Windows executables via Wine when the developer of a game/tool hasn't managed to navigate the complicated maze of "shipping for Linux" thoroughly enough for them.

Was there any need for that? You seem to be getting weirdly personal about this.

> Moving forward, can we agree to keep reports to "here's what I'm seeing / here's what I expected"? Blanket statements are not really helpful, and are certainly not the tone I'd like to encourage in the issue tracker.

Again, getting weirdly personal. It was a mistake in how I thought the app worked, nothing more.

Sorry for trying to help.
