### ISSUE TITLE
🏁 Feedback v25.4.1

### ISSUE THREAD

**Issue by McClan3** [itchio/itch#2500]
Event log:

```
TypeError: Cannot read property 'pid' of undefined
    at Timeout._onTimeout (C:\Users\rener\AppData\Local\itch\app-25.4.1\resources\app\dist\main\main.bundle.js:41557:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by leafo** [comment]
Are you using any virus or security software on your computer? Can you try disabling it and testing again? 

This error suggests that a process that the itch app tried to start was unable to start, likely related to it being blocked by the system or third party security software. Sadly, due to the wide range of how third party security software tends to work (and not work), we can't really offer support for your setup.

Generally we recommend you work backwards by temporarily disabling any third party security software, then test if the app can work, to see if you can narrow down the cause of the issue. We ask that you entirely disable it the security software, and not try to add an exception, since it's easy to incorrectly add an exception, or we've even seen cases when added exceptions do not work.

We can't offer any additional support until you've confirmed you've tested the app with third party software completely disabled.

In itch v25, the main log is in `$XDG_CONFIG/.config/itch/logs/itch.txt` on Linux, `%APPDATA%/itch/logs/itch.txt` on Windows, `~/Library/Application Support/itch/logs/itch.txt` on macOS. You may be able to get more information by reading the logs

Thanks
