### ISSUE TITLE
🏁 Feedback v25.4.1

### ISSUE THREAD

**Issue by 0J3** [itchio/itch#2505]
Event log:
```
TypeError: Cannot read property 'pid' of undefined
    at Timeout._onTimeout (C:\Users\Lannan\AppData\Local\itch\app-25.4.1\resources\app\dist\main\main.bundle.js:41557:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

Reproduction steps:
1. Download the installer for windows
2. Run it
3. Open the itch.io app
4. It should show something like this: ![image](https://user-images.githubusercontent.com/67464646/93665790-a5ed4a80-fa79-11ea-968d-b31eee33b668.png)
5. See Crash

Crash Screen:
![image](https://user-images.githubusercontent.com/67464646/93665811-cb7a5400-fa79-11ea-893a-df0b28525e88.png)

System Information:
- Platform: Microsoft Windows 10 Pro N (with media pack installed)
- Version: 10.0.19041 Build 19041
- Processor: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz, 3392 Mhz, 4 Core(s), 8 Logical Processor(s)
- Secure Boot: Off
- Windows Dir: C:\WINDOWS
- System Dir: C:\WINDOWS\system32
- Locale: United Kingdom
- Installed Physical Memory: 16.0GB
- Total Physical Memory: 15.9GB
- Available Physical Memory: 3.81GB
- Total Virtual Memory: 46.9GB
- Available Virtual Memory: 21.3GB
- Env Variables:
![image](https://user-images.githubusercontent.com/67464646/93665927-8b67a100-fa7a-11ea-9e05-0f9f76f1e5a9.png)

App Version: 25.4.1

**Comment by leafo** [comment]
Are you using any virus or security software on your computer? Can you try disabling it and testing again? 

This error suggests that a process that the itch app tried to start was unable to start, likely related to it being blocked by the system or third party security software. Sadly, due to the wide range of how third party security software tends to work (and not work), we can't really offer support for your setup.

Generally we recommend you work backwards by temporarily disabling any third party security software, then test if the app can work, to see if you can narrow down the cause of the issue. We ask that you entirely disable it the security software, and not try to add an exception, since it's easy to incorrectly add an exception, or we've even seen cases when added exceptions do not work.

We can't offer any additional support until you've confirmed you've tested the app with third party software completely disabled.

In itch v25, the main log is in `$XDG_CONFIG/.config/itch/logs/itch.txt` on Linux, `%APPDATA%/itch/logs/itch.txt` on Windows, `~/Library/Application Support/itch/logs/itch.txt` on macOS. You may be able to get more information by reading the logs
