### ISSUE TITLE
Feedback v25.4.1

### ISSUE THREAD

**Issue by zenpiggy** [itchio/itch#2524]
I installed an earlier version of the Itch desktop app in June 2020 on Windows 7. It worked fine. At some point I guess it was auto-updated to v25.4.1, and when I tried to start the app yesterday, I got just a black screen that needed to be process-killed to exit. I tried to uninstall/reinstall today. I had to disable my firewall program temporarily to allow the app to install correctly, and it seemed to work properly after the installation was finalized. But subsequent attempts to run just give me the same black screen as before.

Future iterations of the app might be better served by not forcing auto-updates because "newer" can also mean "buggier".

Also, the initial installation should take into account firewall programs that do not allow remote connections by new software until explicitly whitelisted. Attempt the remote connection multiple times, then error out gracefully if unsuccessful.

**Comment by leafo** [comment]
We require updates since older versions of the app are deprecated for security reasons. Sorry you're having an issue. Are you able to collect any logs  to share? Typically you can find them in `%APPDATA%/itch/logs/itch.txt`

Regarding the firewall issue, it sounds like you're using third party firewall software, as Windows generally will prompt its own dialog when a new app is trying to access the network. You may want to look into how your firewall software is configured. Sadly, due to the wide range of how third party security software tends to work (and not work), we can't really offer support for those kinds of setups.

Generally we recommend you work backwards by temporarily disabling any third party security software, then test if the app can open, to see if you can narrow down the cause of the issue.

Thanks
