### ISSUE TITLE
Access Denied in Games

### ISSUE THREAD

**Issue by IDontKnow218** [itchio/itch#2530]
Everytime I play a game it says Access Denied. I contacted the games devolopers and he/she doesn't know how to fix the problem.

**Comment by leafo** [comment]
There is not enough information in this issue for us to do anything. Do you have any screenshots or anything? Is this an error from the app or the game?

**Comment by IDontKnow218** [comment]
> There is not enough information in this issue for us to do anything. Do you have any screenshots or anything? Is this an error from the app or the game?

I think the error is from the app because I tried on two games and it says the same thing. I tried the developer and also Microsoft maybe there is a problem in my laptop but they both couldn't help me.![20201028_220747.jpg](https://user-images.githubusercontent.com/72819892/97528496-ee741e00-19be-11eb-8883-281ec8085014.jpg)

**Comment by leafo** [comment]
The error is from the app but it's unlikely that it's our fault, either the game or your computer are blocking the game from running. If you have access to another computer you can try installing the game there to see if it works.

**Comment by IDontKnow218** [comment]
> The error is from the app but it's unlikely that it's our fault, either the game or your computer are blocking the game from running. If you have access to another computer you can try installing the game there to see if it works.

People tell me that the laptop is blocking the game from running, so what do I do to unblock the game?

**Comment by IDontKnow218** [comment]
@leafo

**Comment by IDontKnow218** [comment]
@leafo

**Comment by SolarLune** [comment]
Tagging people repeatedly probably isn't the best way to approach this. You'll have to look at your computer / network and see if there's something that is blocking the execution of the game. Try running it directly and see if you get a different error that you can Google, or see if you have any applications / services running that could block the execution of apps downloaded from the Internet. Being on a school computer or having parental controls / restrictions could be the kind of thing that could cause this issue.

**Comment by leafo** [comment]
Either you have security software on your computer that is blocking the game from starting, or something about you installation is user computer has been modified from defaults which is blocking the expected permissions of the place where the game is installed.

Sadly, because there are so many combinations of states a persons computer can be in, we can't really offer more help than that. I recommend looking into temporarily disabling any security software if you have any, and if that doesn't work you can try a clean wipe of the app and reinstall. That's not guaranteed to fix the problem though, as you computers configuration could be what's blocking it.

If you end up figuring out what the issue was then you can reply here in case if someone else has a similar issue.

Thanks
