### ISSUE TITLE
[Linux] Not starting the right file

### ISSUE THREAD

**Issue by ogbaba** [itchio/itch#257]
The software doesn't launch the right file, the shell script that should be launched doesn't start but the binary does, so the game doesn't work (launching the shell script from the folder works by the way)

[5ZcvrV7AXeW1sytL.txt](https://github.com/itchio/itch/files/72548/5ZcvrV7AXeW1sytL.txt)

Well it seems that the shell script is not even detected, even if it can be executed (+x)
game is http://pougetgames.itch.io/pong-2-players

**Comment by baptistepouget** [comment]
Well it seems that the shell script is not even detected, even if it can be executed (+x)

**Comment by fasterthanlime** [comment]
@baptistepouget I recommend reading #86 to find out the ideal linux packaging setup.

Your shell script, does it start with a shebang? e.g. `#!`

``` bash
#!/bin/sh
echo "Launching, etc."
```

That's how the app detects them (it doesn't pay attention to the executable bit, since it could either be mistakenly on for no-executables, or off for executables if compressed with some ancient/bad archivers)

**Comment by ogbaba** [comment]
Thanks I added this line and now it works fine !

**Comment by fasterthanlime** [comment]
@baptistepouget awesome, thanks for reporting back! :star2:
