### ISSUE TITLE
Installer fails to start on windows xp

### ISSUE THREAD

**Issue by CyberKiller40** [itchio/itch#270]
The installer refuses to start on windows xp, it pops up a window saying to use a newer version. Can you override it somehow to skip this check? The client itself most probably will run.

Or maybe just provide a zipped archive with the client without an installer.

**Comment by fasterthanlime** [comment]
Unfortunately, no, it won't :(

It's not the installer's fault — see the full discussion in #156

the tl;dr of it is that Electron requires Win7 or higher.

**Comment by CyberKiller40** [comment]
Is this Electron thing some kind of framework or something? I never heard of it, but according to links in that other issue, they seem to be hell bent on supporting some useless touchscreen stuff instead of usable platforms, pointing out that it's ole and EoL. Win7 is also EoL, and nobody seems to notice. Not a really friendly piece of software IMHO.

A shame, really, cause a lot of indie games run very good on older systems :-(. I keep winxp only for the legacy stuff, that doesn't run on my main OS, which is OpenSUSE.

**Comment by fasterthanlime** [comment]
> Is this Electron thing some kind of framework or something?

Kind of — electron is basically libchromiumcontent + node.js, allowing you to build an UI using web technologies and use the vast amount of javascript libraries available on npm to build the 'backend' (what doesn't run on the browser process). It's championed by companies like GitHub & Slack.

There are many arguments that can be made against it, but I would never have been able to build itch in 3 months if it wasn't for electron. There is no plan to move away from it as its only competitor, nw.js, seems inferior to me in many aspects.

I understand the frustration that comes with discovering that some piece of software isn't compatible with another — in the case of GitHub, I assume that with their limited means (in developing a software development framework, itself used in a text editor (atom), that is a borderline distraction in their main business (git hosting)), aka almost exclusively one employee, they choose to focus their resources however they think is best.

And so far, I've been okay with their priorities — ever since electron v0.32.0, the changes/fixes have been mostly ahead of my wishes. When they say it's "not supported", it means they decided X was outside of their scope, it doesn't mean it's technically impossible. Electron is open-source, so someone could potentially produce a stripped-down build of it that runs on Windows XP or Vista — but with my limited resources, I probably wouldn't want to rely on a third-party fork of it, and stay with mainline instead.

Hopefully that comment doesn't come off too preachy, it's just that I really really appreciate the work the electron contributors have been doing, and I hate to see it shot down because of this. I'm sorry you can't use it on XP. (If it's any consolation, it probably runs fine on OpenSUSE!)

**Comment by CyberKiller40** [comment]
Yes it runs ok on OpenSUSE, but most itch.io games don't, that's why I tried to use the client on this legacy OS that I keep.
