### ISSUE TITLE
[Feature] Do not hide my bundles

### ISSUE THREAD

**Issue by ShalokShalom** [itchio/itch#2798]
HI :)

I am aware, that you hide the bundles, to not flood my library. 
Honestly, I am quite a bit wondering, how I am supposed to access the bundle in the future. 
Until now, the only way I could figure out, that lets me access it, is by clicking on the currently still running sale. 

Am I supposed to save the URL? Forgive me, I like the convenience of actually having a button, a menu point or anything like that, that lets me access the bundle, that I bought. 

I am also actually fine with "flooding my library"

**Comment by Gaboris** [comment]
Same. I would REALLY appreciate the option to add all my games from these bundles to my library at once. I don't have the time to click on each individual game in the list just so the system can load it in.

This was actually a promised feature back when the first 1.000 games bundle was made, but then the line about this in the bundle's description about this was "mysteriously" removed. 😏

**Comment by leafo** [comment]
At the moment the app does not have a separate section for bundles. However, on the site you can access your purchased bundles on this page: https://itch.io/my-purchases/bundles

Regarding a way to copy a bundles contents into your library, it's not something we will be adding, rational is discussed here: https://itch.io/post/5583919

> This was actually a promised feature back when the first 1.000 games bundle was made, but then the line about this in the bundle's description about this was "mysteriously" removed.

Nothing was mysteriously removed, and nothing was promised. We put up a notice saying we may consider it, we considered it, and it's not something we will be adding. See the link above. Please don't hijack other issues with your own requests. Thanks

Although in the future we'll likely have dedicated section for bundles, I'm closing this ticket since it's off topic from that

**Comment by ShalokShalom** [comment]
> Although in the future we'll likely have dedicated section for bundles, I'm closing this ticket since it's off topic from that

Can I have specifics of that?
