### ISSUE TITLE
Install Game Version fails to show anything

### ISSUE THREAD

**Issue by CaptDedEyes** [itchio/itch#2978]
Whenever I attempt to download certain games (this doesn't happen with every game) the version install list fails to populate. This then returns an error whenever I try to download the game.

![image](https://github.com/itchio/itch/assets/70081491/a36235e8-5280-4565-a546-5e0526160cc5)
![Screenshot 2023-12-31 134812](https://github.com/itchio/itch/assets/70081491/e368a27c-6356-48ac-81f2-19baed6a4d25)

**Comment by alts** [comment]
This occurs when there's no downloadable file for the current platform. As of 889280f32457716b6e1c9c2433ca20582e67e33d, the "Install" button is now greyed out, and we show an error message of "No compatible downloads were found". I hope that's a better experience than this one, though the drop down list will still be empty.

This is easiest to see for Cruel World, which intentionally has had all of its downloadable files removed, since the game is "over".
