### ISSUE TITLE
App install failed (no items in Install combolist)

### ISSUE THREAD

**Issue by SeregaKR** [itchio/itch#2999]
Some applications can not be installed. The Install combolist does not contain anything (Only Select is visible).

When you press Install regardless, the app gives you the error.
![изображение](https://github.com/itchio/itch/assets/1452103/e28a4518-2621-479b-9e2a-69b456d760e2)
![изображение](https://github.com/itchio/itch/assets/1452103/dafd3521-7242-4760-abcf-26528eba36f2)

The games so far are:
- https://st-sinovar.itch.io/gods-of-savvarah-part-i
- https://ruttingroads.itch.io/aftersoul
- https://hyperwolfstar.itch.io/brafords-house-of-beef

**Comment by SeregaKR** [comment]
Same as #2978

**Comment by alts** [comment]
This occurs when there's no downloadable file for the current platform. As of 889280f32457716b6e1c9c2433ca20582e67e33d, the "Install" button is now greyed out, and we show an error message of "No compatible downloads were found". I hope that's a better experience than this one, though the drop down list will still be empty.

This is easiest to see for Cruel World, which intentionally has had all of its downloadable files removed, since the game is "over".

**Comment by SeregaKR** [comment]
> This occurs when there's no downloadable file for the current platform. As of [889280f](https://github.com/itchio/itch/commit/889280f32457716b6e1c9c2433ca20582e67e33d), the "Install" button is now greyed out, and we show an error message of "No compatible downloads were found". I hope that's a better experience than this one, though the drop down list will still be empty.
> 
> This is easiest to see for Cruel World, which intentionally has had all of its downloadable files removed, since the game is "over".

In such a case, it'd be convenient to have a way to add the game manually (e.g., by browsing the folder and adding it to the app).
