### ISSUE TITLE
[linux] game Red Eclipse broken for v0.11.3

### ISSUE THREAD

**Issue by Seegras** [itchio/itch#304]
:rotating_light: Game [Red Eclipse](http://redeclipse.itch.io/red-eclipse) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/b4ef60b08cff6f630094).

:running: Can't download via itch client, apparently thinks size should be -1.

**Comment by fasterthanlime** [comment]
Hey, thanks for your report! :star2: 

Red Eclipse uses external uploads and in them it puts an indiedb download page, which doesn't serve a file but rather a page which you have to wait on and click a button.

So, Red Eclipse is broken, the app is working as intended here: http://www.indiedb.com/downloads/start/87523

I'd suggest that the developer directly uploads the game to itch or uses a file host that actually speaks HTTP.

**Comment by qreeves** [comment]
@Seegras We at Red Eclipse apologise for the inconvenience, and I have now fixed the issue. We highly recommend reporting any problems regarding our project to our [Discussion Area](http://redeclipse.net/discuss) so we can action it better. I only became aware of this because I was included in #1609
