### ISSUE TITLE
[win32] assets Font Bundle! broken for v0.11.3

### ISSUE THREAD

**Issue by local-minimum** [itchio/itch#308]
:rotating_light: Game [Font Bundle!](http://somepx.itch.io/pixel-fonts) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/7ae95463e282416ac676).

:running: There are two problems:

a) I didn't understand/see that the icon was a broken heart and tested pressing it. This caused the item to become flagged as broken without warning and without way to say that it is unbroken

b) Since this asset actually isn't executable, it would be really neat after installation if upon clicking on an item which itch can't launch automatically, that the default file-browser was opened to the install location

**Comment by fasterthanlime** [comment]
> a) I didn't understand/see that the icon was a broken heart and tested pressing it. This caused the item to become flagged as broken without warning and without way to say that it is unbroken

The original icon was probably just the checkmark that displays on the "Launch" button. It was then marked as broken because it couldn't launch — and you can retry launching it with the 'refresh' icon (circular arrow) — I'm not sure it worked that way exactly in v0.11.3, but that's the behavior in v0.12.4 at least

> b) Since this asset actually isn't executable, it would be really neat after installation if upon clicking on an item which itch can't launch automatically, that the default file-browser was opened to the install location

Completely agreed! Closing this issue in favor of #96 though :)
