### ISSUE TITLE
failed to launch install

### ISSUE THREAD

**Issue by salsasteve** [itchio/itch#3122]
Something went wrong

itch-setup, v1.26.0, built on Apr 21 2021 @ 20:48:11, ref 48f97b3e7b0b065a2478811b8d0ebcae414845fd

Get "https://broth.itch.ovh/itch/windows-amd64/LATEST": dial tcp: lookup broth.itch.ovh: no such host
While performing GET request to https://broth.itch.ovh/itch/windows-amd64/LATEST
while getting latest version
Error during warm-up

**Comment by Predatorie** [comment]
I verified the same issue with the Windows and Linux installers.

**Comment by lexi-the-cute** [comment]
yep. the dns server for it is down atm. you may have to manually upload a copy of the butler binary to your CI. if it's still down by the time Monday rolls around, i'll have to upload a copy somewhere to access via Github Actions.

https://itchio.itch.io/butler is where an official download can be found that is not down (although not easily automatable)

**Comment by PyromaniacMariner** [comment]
having the same issue; no ping from the server

**Comment by leafo** [comment]
Try the "bleeding edge" version of itch setup: https://itchio.itch.io/itch-setup

We'll push out fixed release soon, just currently dealing with a DDOS on the site.

**Comment by lexi-the-cute** [comment]
> Try the "bleeding edge" version of itch setup: https://itchio.itch.io/itch-setup
> 
> We'll push out fixed release soon, just currently dealing with a DDOS on the site.

im kinda curious about the details of the DDOS. mainly, i wonder who's doing it and why

**Comment by leafo** [comment]
Please try again, we had some downtime with our legacy update server that was still hard-coded in a few places.

That said, we've since pushed out patched versions of the app and related software. Please make sure you update to the latest version to ensure you don't have any issues accessing the app in the future: https://itch.io/t/4351835/app-and-butler-updates-may-require-manual-intervention
