### ISSUE TITLE
Something Went Wrong: Setup Failed

### ISSUE THREAD

**Issue by teutelquessir** [itchio/itch#3128]
Something went wrong

itch-setup, v1.26.0, built on Apr 21 2021 @ 20:48:11, ref 48f97b3e7b0b065a2478811b8d0ebcae414845fd

Get "https://broth.itch.ovh/itch/windows-amd64/LATEST": dial tcp 143.244.220.150:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
While performing GET request to https://broth.itch.ovh/itch/windows-amd64/LATEST
while getting latest version
Error during warm-up

**Comment by gzaxys** [comment]
having the same problem, from what I found the same thing happened 4 years ago. Its just that the servers are being bombarded with request, so the servers are down. Unfortunately nothing we can do till their up again.

**Comment by Famelardtero** [comment]
у меня также проблема

**Comment by sealthedoor** [comment]
am haveing the same issue with firewall off and on

**Comment by darkfrogstudios** [comment]
Having the same problem unfortunately

**Comment by owllegator** [comment]
yeah i'm having the same problem :(

**Comment by darkfrogstudios** [comment]
Thank you for your email,

We will try to get back to you within 5 business days.

With a warm gamers embrace,
- Dark Frog Studios

**Comment by leafo** [comment]
Please try again, we had some downtime with our legacy update server that was still hard-coded in a few places.

That said, we've since pushed out patched versions of the app and related software. Please make sure you update to the latest version to ensure you don't have any issues accessing the app in the future: https://itch.io/t/4351835/app-and-butler-updates-may-require-manual-intervention
