### ISSUE TITLE
Indicate to launched game that it was started by itch and pass through a userid

### ISSUE THREAD

**Issue by kg** [itchio/itch#357]
It would be great if the itch.io app could pass a special command line flag to the game like `--itchio`, and even better if it also passed through a unique user identifier so that a developer could do automatic cloud saves and stuff.

**Comment by fasterthanlime** [comment]
I'm planning on having the app pass some information to launched items via **environment variables** rather than command-line arguments (which leaves arguments free to be used to tune various in-game things, like `-fullscreen` or `-novideo`)

> that a developer could do automatic cloud saves and stuff.

Actually, the itch client will eventually do that itself. Doing it from a userid would be a security problem, as anyone knowing your itch user_id would be able to steal your cloud saves :)

See this issue for example: https://github.com/itchio/itch/issues/122

**Comment by kg** [comment]
Environment variable sounds sufficient, yeah. I can work with that.

I would definitely find itch-client-based cloud saves etc to be useful, but then someone who gets the game through another client/platform can't access their saves because the itch client isn't running ... :( You're correct that it allows bad actors with your ID to do naughty things, though. Having access to the userid (as in steamapi) would still be very useful, even if the developer needs to do the hard work to authenticate a user once it knows their ID.

**Comment by fasterthanlime** [comment]
(This and #81 are sister issues, commenting to crosslink)

**Comment by fasterthanlime** [comment]
Doing that now via manifest: http://itch.io/docs/itch/integrating/manifest.html

**Comment by fasterthanlime** [comment]
API integration solves that problem, shipped in v18: https://itch.io/docs/itch/integrating/manifest.html
