### ISSUE TITLE
[darwin] game Bloodungeon broken for v0.12.3

### ISSUE THREAD

**Issue by astra-midnight** [itchio/itch#365]
:rotating_light: Game [Bloodungeon](http://xaychru04.itch.io/bloodungeon) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/ef75cc1512bd20274bfe).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
This game is broken because its Soundtrack is tagged as being a native build for Windows, Mac, Linux, and Android (which isn't true) — and the app does not support HTML games yet.

The developer should stop tagging the soundtrack as such, & the game will start working as soon as itch supports flash games :)
