### ISSUE TITLE
Have app pick 32 or 64-bit download from upload metadata

### ISSUE THREAD

**Issue by LiamDawe** [itchio/itch#419]
starship command (http://evglabs.itch.io/starshipcommand) won't launch, and it doesn't give me the option to send a bug report either.

Ubuntu 15.10 64bit.

**Comment by fasterthanlime** [comment]
It's probably downloading the 32-bit version

I'll fix the report flow when the bug crashes, but for now, could you manually post the log you get with Alt-clicking the thumbnail? That'd be helpful.

**Comment by fasterthanlime** [comment]
Opened #423 for the flow thing, let's not tackle two separate problems in the same issue

**Comment by LiamDawe** [comment]
Uh sure here: https://gist.github.com/LiamDawe/e3aa4f227020fe3acfcb

**Comment by fasterthanlime** [comment]
Just to bring closure to this issue:

It wasn't downloading the 32-bit version, it was just launching `nacl_helper` instead of the actual game executable.

This [is no longer an issue](https://github.com/itchio/itch/blob/c5d0fa6a89071f185516ee93dcf0b2c094321797/appsrc/tasks/launch/poker.ts#L222-L224).

Also, I just committed code to prefer 64-bit binaries on 64-bit linux, when both 32 & 64 binaries are present. And I'll also give Linux the same treatment as Windows at download time, which is: if there's both 32 and 64-bit downloads available, hide the 32-bit one on 64-bit linux.

Anyway, the game works great :)
