### ISSUE TITLE
[darwin] game STAR GUARD broken for v0.13.2

### ISSUE THREAD

**Issue by geekytime** [itchio/itch#459]
:rotating_light: game [STAR GUARD](https://lorenschmidt.itch.io/star-guard) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/d2debb145691826f258f).

:running: Playing on a Mac...

**Comment by geekytime** [comment]
I got it to play big digging through the logs and finding where it installed it. There's no executable, it's an html file. Does the itch app support that?

If not, can I maybe add support for it? :smile_cat:

**Comment by fasterthanlime** [comment]
@geekytime already in master! Will release a version with it once I feel comfortable / finish up some other stuff!

**Comment by geekytime** [comment]
I just found that PR.

https://github.com/itchio/itch/pull/328

**Comment by fasterthanlime** [comment]
HTML game support has been merged & shipped since v0.14.x, but I think Star Guard requires flash, so it still might not work.

Supporting flash games is not part of our roadmap for now, but nothing prevents the creator from releasing a native version for linux & mac (that includes a flash player, like the original Binding of Isaac did, for example.)
