### ISSUE TITLE
Text game for Windows has no window (The Iron Growler)

### ISSUE THREAD

**Issue by philroyer** [itchio/itch#514]
The game says its running but nothing shows up. It's running in the task manager but with no user facing window. 

https://littletinman.itch.io/the-iron-growler

**Comment by fasterthanlime** [comment]
Ah, I'm assuming that's a command-line windows app. Will have to investigate this one

**Comment by philroyer** [comment]
Yes, it's a command line app. Not sure if there is a proper way to go about that kind of thing with itchio? In other words, what have others done?

**Comment by fasterthanlime** [comment]
I've already seen a bunch of other text games:
- https://severalbytes.itch.io/willow
- https://samgeen.itch.io/hack-and-slash

I don't remember what their behavior is on Windows. It should be possible for the itch app to detect command-line executables and run them in a cmd.exe window instead of just spawning them.

**Comment by alexnask** [comment]
@fasterthanlime This appears to have been fixed (by adding console = true to the manifest aciton).
