### ISSUE TITLE
[win32] game Labyrinth Larry broken for v0.13.2

### ISSUE THREAD

**Issue by mbublitz** [itchio/itch#540]
:rotating_light: game [Labyrinth Larry](https://fameca.itch.io/labyrinth-larry) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/75435da9e405e60a5d59b40c6352aad7).

:running: Any additional details can go here!

I just tried to use your program to test downloading/installing my game file, but it failed on me. It seemed like it downloaded my install file completely, but there is no install file in the directory it went to.

**Comment by fasterthanlime** [comment]
@mbublitz A simple fix is to upload your game as a simple .zip file, without an installer. See https://docs.itch.ovh/itch/master/integrating/platforms/windows.html for details.

InstallShield installers aren't officially supported because they can't be reliably made to a) silently install to b) a specified directory.
