### ISSUE TITLE
Generate proper .deb packages (drop fpm)

### ISSUE THREAD

**Issue by darealshinji** [itchio/itch#570]
Checking the current package `itch-canary_0.14.38-canary_amd64.deb` with lintian gives me a lot of warnings, mostly about stuff being installed into `/opt`, which is considered very bad in Debian packaging.
Another issue I see is that the `Depends:` field is almost empty.
Here's a full log: [itch-canary_0.14.38-canary_amd64.deb-log](https://gist.github.com/darealshinji/7f68f3736167a250ae3a799721a2fe0f#file-itch-canary_0-14-38-canary_amd64-deb-log)

I've build my own version and got rid of all tags eccept for `embedded-library`, which I have overridden instead. See [itch_0.14.38_amd64.deb
-log](https://gist.github.com/darealshinji/7f68f3736167a250ae3a799721a2fe0f#file-itch_0-14-38_amd64-deb)
I'm using [my own buildsystem](https://github.com/darealshinji/debian-packaging/tree/master/games/itch) to build the package, but maybe you can adopt something from it.

**Comment by fasterthanlime** [comment]
@darealshinji if you're willing to help with this, I'd be happy to integrate a more debian-y version to generate our debs.

Can you ping me about this again in two weeks if I haven't gotten back to you yet?

**Comment by darealshinji** [comment]
Sure, I'm glad if I can help.

> Can you ping me about this again in two weeks if I haven't gotten back to you yet?

Yes. I'll save this issue in my bookmarks.

**Comment by fasterthanlime** [comment]
> Yes. I'll save this issue in my bookmarks.

👍 thanks

**Comment by darealshinji** [comment]
Have a look at the build stuff I've added: https://github.com/darealshinji/itch/tree/packaging
Run `release/debian-build-package.sh` on a Debian-based system to build a package. I've also added some comments to that script.

**Comment by darealshinji** [comment]
Here's a script that creates a .deb more strict to the Debian packaging guidelines without any Debian-specific tools: https://github.com/darealshinji/itch/blob/packaging/release/debian-build-package-non-debian.sh
All you need is `fakeroot` and `ar` to be installed.

Should I open a pull request?

**Comment by fasterthanlime** [comment]
> Should I open a pull request?

I'll merge from your fork as needed (it'll still give you proper attribution). Everything is looking good, looking forward to try it!

**Comment by fasterthanlime** [comment]
Wanted to fix a few issues before looking at this properly, got carried away, it's now 1:20AM :) won't have time to integrate that for the next stable, but shooting for the one after that.

**Comment by fasterthanlime** [comment]
Looking at it more seriously now:
- I see you're grabbing+building sassc, but we're not using it anymore - currently using node-sass (which downloads its own sassc, compiles it if there aren't any prebuilt versions available). I'll try removing it, see if everything's fine.
- The `changelog.in` solution is pretty minimal, I should look into generating a proper one. The issue here is that the one generated on CI is often edited by hand before I publish the release on GitHub (which in turns lets our update server know about the new version, etc.). Maybe it should be the other way around - changelog file in the repo, from which github release notes are generated. Probably out of scope for reviewing this.
- I'm ignorant of proper maintainer/mention etiquette - I may be the app's maintainer, but that is a tremendous contribution to our packaging practices - where would be the proper way to mention that (in the deb package)? that also reminds me I was thinking about a `CONTRIBUTORS.md` file, but perhaps https://github.com/itchio/itch/graphs/contributors is enough for now.

Going to integrate it with CI scripts now!

**Comment by fasterthanlime** [comment]
I'm going to have to adjust to build the `itch_canary` packages too ([docs](https://docs.itch.ovh/itch/master/installing/canary.html)), they're designed to be installable side-by-side.

**Comment by fasterthanlime** [comment]
Now completely integrated into the new CI/CD pipeline! 🎉
