### ISSUE TITLE
APP not installing correctly

### ISSUE THREAD

**Issue by crowhound** [itchio/itch#590]
When I tried downloading the itch.io app on my desktop when it starts to install it hangs on this screen
![itc app](https://cloud.githubusercontent.com/assets/11248839/15027709/b6b59b76-120a-11e6-8b15-c5667d13b371.PNG)

After a couple seconds it crashes and closes itself.

I am trying to run it on a windows 8.1 OS

The app version is as following 
![itch app version](https://cloud.githubusercontent.com/assets/11248839/15027753/e54b49f4-120a-11e6-8831-512fa6fccc30.PNG)

**Comment by fasterthanlime** [comment]
I see the issue, working on a fix

**Comment by fasterthanlime** [comment]
More details on the issue:
- The issue only affected fresh installs of itch (ie. on computers where itch was never installed / ran at all)
- The app was trying to access some files under `%USERDATA%/itch`, and that failed, since the directory did not exist.
- v16.1.0 fixes the issue (still being built/deployed at the time of this comment.)

**Comment by fasterthanlime** [comment]
v16.1.0 is out, let me know if you still experience the issue @crowhound!
