### ISSUE TITLE
Clicking "View creator profile" always opens new tab

### ISSUE THREAD

**Issue by Deozaan** [itchio/itch#642]
Clicking the dropdown next to my name in the corner and selecting "View creator profile" will always open a new tab, even if I'm currently viewing a tab of my creator profile.

Interestingly, using the "View community profile" button which is currently broken (see #631) and gives me a 404 error will just open/focus that same 404 error tab. But if I correct the address to actually view my community profile, clicking the "View community profile" button will open a new 404 error tab.

Itch 17.2.0

**Comment by fasterthanlime** [comment]
I'm not sure it's a bug. Maybe it should open in the current tab instead, whatever the current tab is, but that's a matter of taste I suppose?

**Comment by fasterthanlime** [comment]
> whatever the current tab is

(Except if it's one of the 'essentials' tab)

**Comment by Deozaan** [comment]
I figured it would remember tabs. Especially since opening the 404 error tab always focuses the same tab instead of opening a new one. It also has a different tab icon.

Does Itch make use of HTML targets? Like `<a href="somedomain.com" target="profile">`

If this is working as expected, go ahead and close. I was just confused because of the inconsistent behavior.

**Comment by fasterthanlime** [comment]
> Especially since opening the 404 error tab always focuses the same tab instead of opening a new one. It also has a different tab icon.

Well, 'View creator profile' opens `users/:user_id`, whereas 'View community profile' opens `url/:creator_profile_url`, and those do behave differently (so that clicking a game in your library brings up an already-opened game tab, etc.).

Maybe having a specific prefix for community profiles would be meaningful (`community-profiles/:user_id`?) but also require server-side support: currently https://itch.io/profile/fasterthanlime has `<meta name="itch:path" content="users/29789">`

**Comment by fasterthanlime** [comment]
In v25, "View creator profile" opens in the current tab. (Also tabs are disabled by default).
