### ISSUE TITLE
Performance degradation when running development version of itch

### ISSUE THREAD

**Issue by quyse** [itchio/itch#700]
When I try to run development version of itch (via `npm start` in git cloned itch directory), performance is degrading very fast. First half a minute I can click through UI controls and they work, then it becomes harder and harder i.e. I click on a tab, and it switches after 10 second delay, until eventually the app becomes completely unusable (i.e. ~1 minute delay for every action, horribly lagging `hover` animation, etc).

`htop` shows that `electron --type=renderer` process is eating 100% CPU. I tried to profile itch with embedded tools (Shift+F12), but not seeing anything suspicious, javascript doesn't take much of the time. I tried both Linux and OS X. Also I tried both `electron-prebuilt@1.2.0` (recommended on the Getting Started page) and `electron-prebuilt@1.2.2` (latest), with the same effect.

Maybe it's known problem? I'm not very familiar with electron.

The strange thing is that release version of itch app (downloaded from itch.io) works perfectly for me on all my systems.

**Comment by fasterthanlime** [comment]
That would be a side-effect of the redux dev tools (they keep accumulating state changes, resulting in a large DOM). I usually run the app with 'NODE_ENV=production' to avoid this!

Since I haven't used the redux dev tools in a while, I'm considering removing them completely.

Another source of slowness in dev is react PropTypes checking and other various warnings. I'm currently adjusting many things in the app, including performance-wise, so now is a good time to experiment with this!

**Comment by quyse** [comment]
Cool, `NODE_ENV=production` helped a lot, it's running perfectly now like the release version. Sorry for bothering you with stupid things!

**Comment by fasterthanlime** [comment]
That's not stupid at all :) I find it ridiculous that it has such a performance impact. Maybe it's a symptom that our messages are too fat (but a lot of things go through there - the entire local db (one diff at at time), entire sets of i18n strings for two locales if you're on non-English..), maybe not.

If it's just the redux devtools I can make them opt-in with an environment variable - again, I haven't used them in forever (nice in theory, impossible to use in a sufficiently complicated app)
