### ISSUE TITLE
Writing to save folder (also sandbox question)

### ISSUE THREAD

**Issue by martymagaan** [itchio/itch#716]
I have my save folder kept within my game's folder, but the game doesn't seem to be able to write any save files (xml) to it when launching through the itch app. 

I looked through the documentation and figured it might have something to do with the sandbox, so I added the "itch-player" user via the command line as directed. The user was created successfully, but the C:\Users\itch-player directory doesn't seem to exist.

Anyway, I'm not exactly sure what my question is regarding sandboxing haha other than if it has something to do with why my game can't write save files through the app, and if so, how I can get my saved games working.

Thanks in advance!

**Comment by fasterthanlime** [comment]
Hey @nlert!

Although the sandbox is present in the docs right now, it's not in any stable builds of the app at the time of this comment, so it definitely can't be that.

However, writing saves to the game's folder is a bad idea in general — and definitely won't work later, with the sandbox enabled.

Instead, you should be using calls like [SHGetFolderPath](https://msdn.microsoft.com/en-us/library/windows/desktop/bb762181%28v=vs.85%29.aspx) or more simply read environment variables like `%APPDATA%`.

Ideally, your game should only write to `%APPDATA%\com.yourcompany.YourGame` folder. This corresponds to something like `C:\Users\foobar\AppData\Roaming\com.yourcompany.YourGame` — but don't assume it's this exact path, always rely on the environment to give you the proper path instead, so that your game runs anywhere.

It would be helpful if you said which game engine or technology you're using, so that I may point you in the right direction — most engines/libraries have an easy way to do this, as it's a very common problem. (Unity does things right by default, for example).

**Comment by martymagaan** [comment]
Ahhh, I see. For this game I was using LibGDX (for java). I think I can figure it out from here though. Thanks for the quick response! I'll see if I can get it working first before closing this, in case I have to ask something else.

**Comment by fasterthanlime** [comment]
@nlert libgdx is Java, here's the best way to go about it: http://gamedev.stackexchange.com/a/23054

**Comment by fasterthanlime** [comment]
Hmm I spoke too soon: user.home will probably just give you `C:\Users\foobar`.

**Comment by fasterthanlime** [comment]
@nlert were you using libGDX-specific methods from https://github.com/libgdx/libgdx/wiki/File-handling or plain Java classes? I don't know what GDX's "local files" behavior is, but it might write to the right directory already (and you'd get Android support for free!)

**Comment by martymagaan** [comment]
I used plain Java classes. LibGDX's local file writing just writes to the same directory that the game application is located in.

Anyway, I figured out how to write files to a path using the APPDATA variable and the saves work now for Windows. I just have to make equivalent working versions for Mac and Linux.

Thanks again for the help!

**Comment by fasterthanlime** [comment]
@nlert Good to hear! For Linux, look into `$XDG_CONFIG_DIR/yourgame` and fall back to `$HOME/.config/yourgame`. For Mac, `$HOME/Library/Application Support/yourgame` is the proper folder.

**Comment by martymagaan** [comment]
Cool, good to know
