### ISSUE TITLE
Adding install locations seems not to work

### ISSUE THREAD

**Issue by ConnorKrammer** [itchio/itch#741]
Just downloaded the latest version of Itch (v18.0.0) with no games installed, and attempted to add a new install location before downloading my games. I navigated to preferences and clicked "Add location", and then selected the folder I wanted to add. This didn't seem to do anything, and the install locations list remained empty. I did not receive an error prompt or notification of any kind.

This occurred on Windows 7.

**Comment by cyxceven** [comment]
Can confirm. Windows 7 as well.

**Comment by fasterthanlime** [comment]
This it the moment I notice I forgot to add an "open app log" button to the app.

Can you post the contents of the relevant .txt file in `%APPDATA%/itch/logs` to https://gist.github.com/, then post that link here?

**Comment by ConnorKrammer** [comment]
Yep. Here you go: https://gist.github.com/ConnorKrammer/5846c3a976006ed4b464dcbe59818f17

Looks like the error is actually related to changing window focus, and not specifically with adding new install locations (the selection of a new install location merely implicitly requiring a change of window focus when the file explorer pops up). When tabbing between the log file and Itch's window, I noticed that it generated an identical error as when going through the install location prompt.

The log file above is a result of the following steps:
1. Launching Itch
2. Clicking "Add new Install Location"
3. Selecting a new folder
4. Closing Itch

**Comment by fasterthanlime** [comment]
Ah, interesting! Looks like the error in question is related to your profile (happened while fetching `dashboardGames`), I'll take a look at what makes it so special monday!

**Comment by fasterthanlime** [comment]
(Just had a similar issue - adding install location seemingly did nothing, I had to try a second time for it to work)

**Comment by ConnorKrammer** [comment]
Any news on this? I've avoided doing anything that might change my profile, in case you still need to take a look.

**Comment by fasterthanlime** [comment]
So, about this:

> Ah, interesting! Looks like the error in question is related to your profile (happened while fetching dashboardGames), I'll take a look at what makes it so special monday!

...this is unrelated. I've found and fixed that issue, but it doesn't seem to have anything to do with install locations.

I'm still not sure what causes the install location area to not refresh sometimes. I've changed the preferences pane quite a bit since 18.2.0, so maybe the issue just doesn't exist anymore in the new version. I ran quite late in releasing it because of #697, took me a lot longer than expected, but it shouldn't be much longer now.

**Comment by fasterthanlime** [comment]
> ...this is unrelated. I've found and fixed that issue, but it doesn't seem to have anything to do with install locations.

If you want to make triple-sure it's unrelated and I didn't just get it wrong, you can create a dummy game page (even empty) from https://itch.io/dashboard and attempt to reproduce the install location issue. This'll make the fetch error go away.

But I think it's unrelated because even if fetching throws, it doesn't propagate any further in the app.

**Comment by fasterthanlime** [comment]
> Just downloaded the latest version of Itch (v18.0.0) **with no games installed**

This is the part I overlooked - when no games were installed ever, it looks like the default %APPDATA%-based install location doesn't appear in the list. preboot should take care of that.

![no-install-locations](https://cloud.githubusercontent.com/assets/7998310/16894519/e3aee51a-4b58-11e6-92eb-7e3ba3cb624e.png)
