### ISSUE TITLE
images don't load on homepage

### ISSUE THREAD

**Issue by leafo** [itchio/itch#763]
Sometimes when the itch.io tab is loaded, the images don't appear. I also notice that there is some app install banner, which I thought was hidden by the app. Refreshing the page fixes it.

The website lazy loads the image when they get into the viewport, so javascript is required for images to appear.

![](http://leafo.net/shotsnb/2016-07-02_17-59-30.png)

**Comment by fasterthanlime** [comment]
This is going to be a thorny one - I've seen it, and the reason is most probably that when tabs load "in the background", the webview width/height is set to 0x0 (as the electron docs say we should do). This probably trips up the 'is this image in the viewport?' code on itch.io.

I'm not sure what is the best way to go about this. Maybe #606 could help..

**Comment by leafo** [comment]
the image loading code knows to re-check everything if the viewport size is changed or the window is scrolled, but resizing does none of these. Additionally new images that I bring into the viewport can never appear.

The reason why I mentioned the banner on top is because you hide it with javascript, maybe there's a js error somewhere that stops the page from being initialized all the way?

**Comment by fasterthanlime** [comment]
> the image loading code knows to re-check everything if the viewport size is changed

clearly you haven't dealt with electron's webview bugs long enough ;) since webviews are actually browser plug-ins, they have many small/tricky issues, and it doesn't seem impossible that the webview resizes without throwing the resize event.

> The reason why I mentioned the banner on top is because you hide it with javascript, maybe there's a js error somewhere that stops the page from being initialized all the way?

I'll look into it, but wouldn't that prevent images from loading when the tab _isn't_ hidden too?

**Comment by leafo** [comment]
> I'll look into it, but wouldn't that prevent images from loading when the tab isn't hidden too?

The error would have to be happening because of side effect of rendering the page at 0x0 I'm guessing

**Comment by leafo** [comment]
BTW: The width/height of the cells on the homepage are controlled by javascript, and they still update on resize. So that code is running fine.

**Comment by fasterthanlime** [comment]
Investigating this, but quick tip for future problems: if you export `DEVTOOLS=1`, you get devtools for the app's interface. If you export `DEVTOOLS=2`, you get devtools for all web tabs too.

**Comment by fasterthanlime** [comment]
bingo

<img width="797" alt="screen shot 2016-07-06 at 18 34 37" src="https://cloud.githubusercontent.com/assets/7998310/16626233/52322d98-43a8-11e6-8d77-23f07ce100e3.png">

**Comment by fasterthanlime** [comment]
apparently, in browser.js, I'm using a `setTimeout(setup, 10)` to replace I with my own instance, looks like the site doesn't like that
