### ISSUE TITLE
App can't seem to install VA-11-Hall-A full game even when owned

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#774]
cf. https://itch.io/t/29183/itch-app-only-installs-demos

**Comment by Aicaya** [comment]
Installs correctly on Linux.

Issue is due to VA-11 Hall-A essentially having two games in one: the Prologue story and the main game (both of which have separate stories and gameplay). A recent update bumped the Windows version of Prologue to the top of the list, which means it's the one that's gonna be downloaded. So it's not a bug with the client - it's something to be brought up to the developer.

Which brings me to a question: To avoid this, why not either A. give the developer an option to choose which version the client will download by default (instead of relying on file order), or B. give users the option to choose which file to download in cases where there are multiple ones (multiple games, separate downloads for 32/64-bit, etc)? Seems that'd solve a good chunk of the issues I've found with certain games.

**Comment by fasterthanlime** [comment]
@ephemeralCuriosities I took your hint:

![screen shot 2016-07-06 at 05 38 20](https://cloud.githubusercontent.com/assets/7998310/16606856/e1b4fde6-433b-11e6-8e5e-36cd7faf5142.png)

Shipping this soon.

**Comment by fasterthanlime** [comment]
Shipped with 18.3.0!
