### ISSUE TITLE
"Last played now" even after two hours from last launch

### ISSUE THREAD

**Issue by 0x0961h** [itchio/itch#812]
- Version: **18.3.0**
- OS: **Windows 8.1 x64**

I opened the game store page in app, installed it, launched, played, closed and saw this:

![image](https://cloud.githubusercontent.com/assets/5813735/16896672/0ba1b46c-4b9a-11e6-94ff-95febbeb60e3.png)
It's okay. But I'm still seeing same "Last played now" message and it's been, like, hour or so. 

Maybe it should change over time? Like,
- now
- 1-10 minute(s) ago
- more than 10 minutes ago
- more than 30 minutes ago
- more than 1-23 hour(s) ago
- and so on

Last one is pretty "corner-case"-ish, but still.

P.S. Important: I didn't navigate away from the store page, I closed the game and switch to my other tasks.

**Comment by fasterthanlime** [comment]
It should definitely change over time. Do you see that happen with all games?

**Comment by fasterthanlime** [comment]
It seems the issue is mostly that the component doesn't re-render ever. If you close the tab & re-open it it'll display the updated duration.

**Comment by fasterthanlime** [comment]
Proof that the underlying logic is sound:

![timeago](https://cloud.githubusercontent.com/assets/7998310/16897001/ae3ac59c-4ba4-11e6-83cc-997685beef16.png)

The fix is to have a `setInterval` on mount that calls `setState` with a timestamp, which forces React to rerender the component. This is what react-timeago but wrapping it in `NiceAgo` ruined it because it doesn't even use react-timeago when rendering the text `just now`.

**Comment by 0x0961h** [comment]
Yeah, it definitely works if I close tab and re-open it after some time. It doesn't update in "real-time", though.
