### ISSUE TITLE
Try to solve as many lintian warnings as possible

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#84]
Those in particular look reasonable:

https://twitter.com/roberto_roch/status/676391039343661056

**Comment by matiasbeckerle** [comment]
Consider using [grunt-electron-debian-installer](https://www.npmjs.com/package/grunt-electron-debian-installer). At least [is setting the mantainer](https://github.com/unindented/grunt-electron-debian-installer/blob/master/tasks/electron-debian-installer.js#L139).

Looks like Atom creates a new file for Linux builds including some lintian overrides... but the ones from screenshots it can't because are considered errors.
- [build process](https://github.com/atom/atom/blob/8fb4e887df800438b2deeb23a2c23004b9ff358a/script/mkdeb)
- [list](https://github.com/atom/atom/blob/master/resources/linux/debian/lintian-overrides)

**Comment by fasterthanlime** [comment]
> Consider using grunt-electron-debian-installer.

I don't really want to move away from fpm, but fpm also allows setting overrides as far as I can tell, we could start copying the set atom is using.

fpm options are in here: https://github.com/itchio/ci.itch.ovh/blob/master/src/jobs/itch.yml

**Comment by fasterthanlime** [comment]
At first glance, it doesn't look as if fpm supports providing lintian overrides

**Comment by fasterthanlime** [comment]
Closing in favor of #570
