### ISSUE TITLE
"Check for updates" doesn't always provide feedback

### ISSUE THREAD

**Issue by IBwWG** [itchio/itch#852]
I have "Production District" and "Defender's Quest: Valley of the Forgotten DX" installed.  The former, if I click it within the itch.io app, then click "Check for update", says "is up to date" in a red popup at the bottom.  The latter just doesn't say anything.  Furthermore, I suspect it's out of date, since launching the game says it's at 2.0.4c which was current IIRC last month some time.  Maybe a "checking for updates...", "found an update, downloading..." is in order?

**Comment by fasterthanlime** [comment]
Looks like the same problem as this: https://itch.io/t/34998/could-not-check-for-updates-options-must-be-an-object?before=5#post-44399

I think I know what's happening, shipping a patch ASAP.

**Comment by fasterthanlime** [comment]
Closed in 0d05ef0706e5a2466ab87006b67c84251b43333c, shipping 18.6.1

**Comment by IBwWG** [comment]
Unfortunately, I'm still seeing this exact behaviour in 18.6.1, with the two above examples.  I just updated to 18.6.1, restarted the itch app, and tried again.  (Win7sp1x64 btw.)

The version it's showing for DQ is "game 69770, version 228906", from June 24th according to the tooltip.  There's no way that's current--I now see on Steam that 2.0.8-something is out now.

**Comment by IBwWG** [comment]
Moreover, I just noticed that my own game, https://ibwwg.itch.io/mathildagame , exhibits a different problem: check for updates succeeds and according to the popup is up to date, but it's not: it cites "game 71524, version 227371/4232" from June 30th, and I've put out two updates for Windows since then.  I do have two Windows channels--a beta releases one and a "bleeding edge" one, but a) the former has been updated twice and b) the latter was only created in August and has since been updated four or five times.

**Comment by IBwWG** [comment]
Although, interestingly, `butler status` shows version 4232 for the windows-beta channel.

And actually launching the game, it's version number is up to date (0.2.4).  So in this case it's a problem with the date in the tooltip on the Version button above "check for update" in the itch app.

**Comment by IBwWG** [comment]
DQ, on the other hand, still says 2.0.4c.

**Comment by fasterthanlime** [comment]
About DQ: is it this one? https://leveluplabs.itch.io/defenders-quest-valley-of-the-forgotten-dx ~~looks like it's currently unavailable for download, you'd have to ask Lars Doucet what's up with that.~~ looks like new purchases are disabled, but as an owner, you can still download it - however there hasn't been any recent updates. Someone should still ask Lars what's up with it.

About Mathilda: 4232 is indeed the latest build for the windows-beta channel, so it looks that's good, the date might indeed be wrong (the app should display the build date, not the upload date - which is in your case is the channel creation date).

Previously, the API didn't expose that - I've patched it so that it does, I'll update the app so that it shows the user_version if it's there, and the build date correctly.

_edit: forgot it was saturday! (had a weird week), sorry for the ping, Lars o/_

**Comment by larsiusprime** [comment]
Hey I'll check in on this on Monday! Thanks for the ping
