### ISSUE TITLE
Document proper linux packaging practices

### ISSUE THREAD

**Issue by charliesgames** [itchio/itch#86]
Would be ideal if we could set a script to execute rather than the executable itself. Not all dependencies can be satisfied by whatever package manager is installed, especially in the case of certain commercial/shareware libs, so being able to set a library path for the main exe is pretty important.

Cheers
Charlie

[edit] Cool app, by the way :)

**Comment by fasterthanlime** [comment]
If there's a shell script at the top-level, it will be executed rather than a binary.

Here's an example of a properly packaged Linux game: http://fasterthanlime.itch.io/behind-the-fence

This makes sure it can be easily launched both with and without itch.

(However, this should be documented somewhere)

**Comment by fasterthanlime** [comment]
Re-opening as I'll be using this issue to track our progress on documenting the process

**Comment by charliesgames** [comment]
Right, ok. I'll take a look. Are there any rules to this? i.e. script has to be the same name as the exe?

**Comment by charliesgames** [comment]
Ah, i see. Would it be possible to add a set named script file, such as launch.sh to override any exe in the top level?

**Comment by fasterthanlime** [comment]
> Are there any rules to this? i.e. script has to be the same name as the exe?

Since whatever I write here will be outdated at some point, here's the actual logic behind it:
- https://github.com/itchio/itch/blob/master/app/tasks/configure/linux.js
- https://github.com/itchio/itch/blob/master/app/tasks/configure/common.js
- https://github.com/itchio/itch/blob/master/app/util/sniff.js
- https://github.com/itchio/itch/blob/master/app/tasks/launch.js

Basically, the shortest path wins. Put your binaries in a subfolder and you'll be fine. No need for the binaries to have a particular name, you're calling it explicitly from the shell script.

Here's how BTF is packaged:

<img width="409" alt="screen shot 2015-12-14 at 19 48 23" src="https://cloud.githubusercontent.com/assets/7998310/11790367/ab3385bc-a29b-11e5-9933-597324b85b21.png">

And its launcher script:

``` bash
#!/bin/bash

cd "`dirname "$0"`"

if [ $(uname -m) == "x86_64" ]; then
        # Print some output to let the user know what's going on
        echo "Running 64 bit"


        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./lib64/
        ./bins/plant64
else

        echo "Running 32 bit"

        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./lib32/

        ./bins/plant32
fi
```

**Comment by fasterthanlime** [comment]
> Ah, i see. Would it be possible to add a set named script file, such as launch.sh to override any exe in the top level?

Sure, but it would have to be a unique name, to make sure it doesn't clash with the rest. Out of curiosity, why would you have control over launch.sh but not another top-level .exe ?

**Comment by charliesgames** [comment]
So i don't have to change my packaging script ;) It's not a biggie really. 

Cheers
Charlie

**Comment by ThomasFOG** [comment]
Hi!

Does the Linux launcher look for ".sh" files, or "#!/bin/bash"? (wondering it the file extension is required)

**Comment by fasterthanlime** [comment]
@mrhelmut It looks for files starting with a hashbang (`#!`), file extension is not taken into account

**Comment by ThomasFOG** [comment]
Great, thanks. :+1:

**Comment by fasterthanlime** [comment]
Ah look we have proper documentation on this now! https://docs.itch.ovh/itch/master/integrating/platforms/linux.html
