### ISSUE TITLE
Persistent data for browser games in the Itch App

### ISSUE THREAD

**Issue by isharacomix** [itchio/itch#861]
I've been playing with RPGMaker MV and PICO-8 and using them to put HTML5 games on Itch. They play very well in both the browser on the website and in the desktop app, but when I close a game in the app, I lose my savefiles.

RPGMaker MV makes use of the LocalStorage API to save games. PICO-8 uses the IndexedDB. Is it possible to have these data stores persist between runs of browser games launched from the app?

**Comment by fasterthanlime** [comment]
Can you give me a test game's itch.io url so I can test it myself? Sessions are supposed to persist to disk (and there's one per game) - maybe I got the electron settings wrong.

**Comment by isharacomix** [comment]
Sure:
- RPG Maker MV Game: http://isharacomix.itch.io/hello-world

To reproduce, start the game, press Escape and save. Then exit to title. Observe that "Load Game" on the main menu is visible. Now quit the game and re-launch it. Observe that "Load Game" is grayed out and unavailable.
- PICO-8 Game: http://isharacomix.itch.io/hello-world-pico

To reproduce, press Enter during gameplay and choose "Save". Move a tile and then choose "Load" - observe that you return to the starting position. Now quit the game and re-launch it. Choose "Load", and observe the game glitch out by sending all sprites to the top left (this is because all of the values in the save file are back to zero).

You can do these same tests in the browser and they work as you would expect so long as you aren't in private mode. I've tested this with both Windows 10 and Ubuntu 14.04.

Thanks so much!

**Comment by fasterthanlime** [comment]
I haven't had a chance to test both games yet (but thanks a lot for the link & detailed steps!), but I did read up on electron docs some more.

Here's the itch code that launches 'html games': https://github.com/itchio/itch/blob/master/appsrc/tasks/launch/html.js

As you can see, we're calling `clearCache` after the game is done running - mostly because, since the game is served from an HTTP server, chrome has its own cache, which persists to disk (because of the `persist:` prefix in the session name), so you end up with two copies of the game on your disk as soon as you launch it (at least, in the worst case, if electron caches everything.)

However, there's another method for [session](https://github.com/electron/electron/blob/9965423c4d51e25294cfd705f49829ee014c59ca/docs/api/session.md), `clearStorageData`, which leads me to believe that `clearCache` shouldn't clear IndexedDB/LocalStorage, only `clearStorageData` with the appropriate options would.

I'll keep looking into it.

**Comment by fasterthanlime** [comment]
New theory: if the game is using cookies for save, since it's served on a different port each time, that might be why!

See on the first launch:

```
[2016-11-05 @ 19:07:02.860] [tasks/launch] serving game on port 61612
```

And on the second:

```
[2016-11-05 @ 19:07:17.581] [tasks/launch] serving game on port 61619
```

_testing testing testing_

Sure enough, forcing the port to 61612 makes the save appear (for the RPG Maker game). I'll try to think of a solution, now that I know where the problem comes from :)

**Comment by fasterthanlime** [comment]
Found a way to make custom protocol works :)
