### ISSUE TITLE
Self-updates on Linux?

### ISSUE THREAD

**Issue by IBwWG** [itchio/itch#868]
I've had a bit of a mixed experience among platforms here.  The Itch app on Windows just updates itself with the click of a button.  But on Linux...

64-bit Ubuntu: it opened a web browser to download a package file, which, when double-clicked, allowed me to install the new version.  It'd be nice to cut the browser.

32-bit Mint: it opened a web browser and downloaded a .tar.xz file, which is even more of a manual process than I went through to install it on Mint in the first place (downloading a `.deb`).

**Comment by fasterthanlime** [comment]
I agree with that feeling! hence #827.

In the meantime: you can actually add our APT repository to get updates with the rest of the system on Debian-based distribution. I just realized it didn't appear in the docs anymore, so I fixed them, here's the right page: https://itch.io/docs/itch/installing/linux/ubuntu-and-debian.html

For Mint: probably in an effort to protect your privacy, Mint browsers don't send User-Agents that we can sniff to identify that it's Debian-based, unfortunately :( that's why you get the .tar.xz instead of the .deb

Ideally I'd like to have the same experience on Linux as one has on Windows/macOS, but we need to build Squirrel.Linux first — closing in favor of #827, which tracks exactly that.

**Comment by IBwWG** [comment]
Oops, sorry.  I did search, but didn't notice that one.

However, the odd thing is, it somehow gave me a .deb the first time from the web site.  But thanks, it will definitely help to put the repo in there.

**Comment by fasterthanlime** [comment]
> Oops, sorry. I did search, but didn't notice that one.

Yup, it was absent from the docs for a while :( fixed in 1d373acc39578ab9117bbc78e6e21d35fdbdb71f

> However, the odd thing is, it somehow gave me a .deb the first time from the web site. But thanks, it will definitely help to put the repo in there.

Another possibilty is [this bit of code](https://github.com/itchio/itch/blob/3f710f689124b7d562e8f9f25b6370ab4c125719/appsrc/reactors/self-update.js#L163) not properly running on Mint. What does `/usr/bin/dpkg --search /usr/bin/dpkg; echo $?` print in a shell?

**Comment by IBwWG** [comment]
Oh I meant I searched for a github issue.  :)

It returns

```
dpkg: /usr/bin/dpkg
0
```

That's interesting that that didn't work...

**Comment by fasterthanlime** [comment]
Yep, that's the expected output, weird indeed. Oh well, I'm really looking forward to an update flow that doesn't require any root access.
