### ISSUE TITLE
support for multiple download games (bundles etc)

### ISSUE THREAD

**Issue by mshimokura** [itchio/itch#929]
When there are multiple downloads available (i.e. https://juegosrancheros.itch.io/fantastic-arcade-2016), it would be nice if you could install multiple of the downloads.
Right now I think I have to uninstall the 'game' before downloading a different item in the bundle.

If you could support installing multiple downloads (maybe a 'manage downloads' to install / uninstall), then picking from a list every time you hit the Launch button it would be nice.

**Comment by fasterthanlime** [comment]
Hey! I agree that would be nice.

Not entirely sure how the UI would look like though! A bunch of things in the sidebar assume a single 'download' is installed for a game.

Our current backend also isn't really suited for "Hosting multiple games on a single page" (ideally the bundle would've been an [actual bundle](https://itch.io/docs/creators/bundles)).

For example, when a new download is added to the page, the app won't be able to tell which game it's an update for (it could do name matching, but that's not reliable).

**Comment by roseroser** [comment]
Yes I agree with this, and We support installing multiple downloads

**Comment by Xananax** [comment]
Some games also propose manuals/music/other goodies, which wouldn't really make sense in a bundle. Or sometimes you'd like to compare the jam version of a game and the final one, etc. How about listing the available downloads in the right bar, even if only the first downloaded would be considered by whatever systems that expect one file only? Have a list of files:

```
| Win Version (downoad)
| Mac Version (download)
| Manual (download)
```

Which become:
```
| (default) Win Version (run) | (check for an update) | (Version)
| Mac Version (download)
| Manual (run) | (check for an update) | (Version)
```
after downloading each. The first downloaded gets the "default" flag, which is what runs when just pressing "launch". Right clicking allows to change which item is "default".


The check/local files/version buttons could just stack to the right of the button, or under it on small resolutions, or show on hover only.

I have 0 idea about the feasibility of this, I don't know the code at all, just trying to answer the UI concern 

I think it would go a long way into mitigating the annoyance of not being able to download different files.

**Comment by fasterthanlime** [comment]
![image](https://user-images.githubusercontent.com/7998310/45637971-15578a80-baac-11e8-8442-0a9dcf322062.png)

boom, v25 is out and it lets you install whatever you want - multiple items even. And then manage each of them separately.

**Comment by Xananax** [comment]
*squeals*

**Comment by Xananax** [comment]
Coming back to this, as there's some confusion about it; I've seen people wonder about it in the Itch Discord too.

I've acquired the [Bundle For Racial Justice and Equality](https://itch.io/b/520/bundle-for-racial-justice-and-equality) (yey for that! You peeps and all participating creators are doing an awesome job).

I find no way to make those games appear in my purchases. The games don't show in my list.

I can access the games by:

- accessing the bundle page, then
- clicking a game

It's a bit bothersome, for the following reasons:

1. I need to remember the bundle's URL (not too much of a problem since the client - very excellently - supports tabs, but most people have them off by default).
2. I can't get a clear count of how many itch games I own. It's way over what I used to own on Steam and GOG combined, but I wanna know by _how much_ (I would also like a counter in the "owned" page, but that's another feature request)
3. If I wonder what to play next, I now have to check 2 different lists
4. Next time you make a bundle, I'll have to _check 3 lists_.

If you feel this warrants a different issue, I can open a new one.

**Comment by fasterthanlime** [comment]
I wouldn't bother opening an issue for that one.

We're painfully aware of the UX issues with the bundle right now - it's the largest we've ever done, we knew going into it there were going to be perf issues with the site, we've been spending time making sure the site stays up for everyone, so compromises had to be made.

We'll definitely address those issues as things calm down - they haven't yet.

**Comment by Xananax** [comment]
Yea, I guessed something like that was happening. Keep up the good work!
