### ISSUE TITLE
Invalid AppStream Appdata

### ISSUE THREAD

**Issue by probonopd** [itchio/itch#937]
Thanks for shipping AppStream Appdata. However, it fails validation by the AppStream CLI tool version: 0.9.4 (the one in Ubuntu 16.04):

```
E - itch.appdata.xml:itch.desktop
    Unknown type '(null)' for <translation/> tag.

W - itch.appdata.xml:itch.desktop
    Found invalid tag: 'languages'. Non-standard tags must be prefixed with "x-".

W - itch.appdata.xml:itch.desktop
    Found empty 'translation' tag.

E - itch.appdata.xml:itch.desktop
    'translation' tag has no 'type' property: 

Validation failed.
Failed to validate AppStream information with appstreamcli
```

**Comment by fasterthanlime** [comment]
Would you happen to have a link to the latest Appdata standard? When I last worked on this, I was struggling to find definitive information.

**Comment by probonopd** [comment]
Linking in @ximion here. He recommends https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps as a starting point.

**Comment by fasterthanlime** [comment]
Here's a good example of my past struggle: appstreamcli chokes on `<languages>`, but it's clearly compliant with this: https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Localization.html

Not sure what's up with our empty `<translation/>` tag though, that can definitely go.

**Comment by probonopd** [comment]
Yes I can feel with you (struggling with outdated documentation and/or tools myself while trying to use AppStream for AppImage) but @ximion is very helpful in addressing these.

**Comment by ximion** [comment]
@fasterthanlime "languages" was invalid for metainfo files until AppStream 0.10 (and the validator didn't even know it was allowed, I fixed that just now), and the `localization` component-type didn't exist until AppStream 0.10 as well.
I bet your metainfo file is also not describing a "localization" component, but rather is of type "desktop-application".

Looking at https://github.com/itchio/itch/blob/master/release/templates/itch.appdata.xml, the `<translation/>` tag is indeed empty. This is usually a serious error, since it will prevent the AppStream metadata extractor from determining the l10n status of the software component.

Validating the file with the newest appstreamcli, I get:

```
W - itch.appdata.xml:itch.desktop.desktop:18
    Found empty 'translation' tag.

W - itch.appdata.xml:itch.desktop.desktop:8
    The component ID is not a reverse domain-name. Please update the ID and that of 
    the accompanying .desktop file to follow the latest version of the Desktop-Entry 
    and AppStream specifications and avoid future issues.

E - itch.appdata.xml:itch.desktop.desktop:18
    'translation' tag has no 'type' property: 

Validation failed.
```

Which are all valid issues.
(the reverse-domain-name stuff is required for proper Wayland-support (DBus activation) and to follow the AppStream naming guidelines, so it's a very good idea to consider renaming the files.)

**Comment by fasterthanlime** [comment]
> I bet your metainfo file is also not describing a "localization" component, but rather is of type "desktop-application".

Correct! So there's no way to list the languages in which the app is translated, since there's no separate -i18n package?

> (the reverse-domain-name stuff is required for proper Wayland-support (DBus activation) and to follow the AppStream naming guidelines, so it's a very good idea to consider renaming the files.)

I'm willing to do that (although `io.itch.itch` sounds kinda silly), but you might want to fix the Quickstart guide so that its example includes a reverse-domain-name id (instead of `gnome-power-manager`). I'm now seeing the note, but it's easy to miss!

Thanks for the help so far, I'll take another pass at it eventually. Is there an up-to-date "single HTML page" or PDF version of this? https://www.freedesktop.org/software/appstream/docs/index.html

**Comment by ximion** [comment]
@fasterthanlime 

> Correct! So there's no way to list the languages in which the app is translated, since there's no separate -i18n package?

No - the AppStream metadata extractor will determine the l10n status from the translation domain referenced by the `<translation/>` tag.
Additionally, I allowed the `<languages/>` tag for arbitrary components now, feel free to use it (and maybe use a newer validator to validate).

> I'm willing to do that (although io.itch.itch sounds kinda silly), but you might want to fix the Quickstart guide so that its example includes a reverse-domain-name id (instead of gnome-power-manager). I'm now seeing the note, but it's easy to miss!

Good catch! I thought I converted all of these entries, looks like I missed quite a few.

> Thanks for the help so far, I'll take another pass at it eventually. Is there an up-to-date "single HTML page" or PDF version of this? https://www.freedesktop.org/software/appstream/docs/index.html

No, but we could build one if there is interest in one (it's all Docbook afterall).

**Comment by fasterthanlime** [comment]
Closing since we don't ship an official .deb package anymore as of itch v25.
