### ISSUE TITLE
Use HTTPS connect for proxying (tunnel-agent)

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#942]
_Copied from https://github.com/itchio/itch.io/issues/544_:

When requesting an https object through a proxy, the application should use the CONNECT method to establish a pipe to the server, negotiate security and then make object requests.

Instead, the application breaks spec and attempts to make a proxy request of the form: GET https://dl.itch.ovh/...

This is incorrect for (at least) three reasons:
1. If it is requesting private data, that data may be improperly cached by the proxy.
2. Data can be snooped off the wire between the application and the proxy in what is intended to be a secure connection.
3. It basically doesn't work in many proxy configurations, and prevents the application from checking for updates or logging in successfully.

**Comment by fasterthanlime** [comment]
@DancerV I'm interested in fixing this, could you give some more details? What tools did you use to observe the app's behavior? I've been testing proxy support with Fiddler running on another computer of my LAN.

It looks like needle has a [bunch of issues](https://github.com/tomas/needle/search?q=tunnel&type=Issues&utf8=%E2%9C%93) regarding tunnelling proxies (which is what you're referring to right?) — maybe all we need is to swap in the correct agent!

**Comment by DancerV** [comment]
Saw the errors and chased it down in my proxy logs (squid). Here's what they look like:

1476776489.658      0 2001:44b8:418b:1b00:ce4:482b:60d1:85f3 TAG_NONE/501 4088 GET https://dl.itch.ovh/unarchiver/windows-386/LATEST? - HIER_NONE/- text/html
1476776489.715      0 2001:44b8:418b:1b00:ce4:482b:60d1:85f3 TAG_NONE/501 4079 GET https://dl.itch.ovh/elevate/windows-386/LATEST? - HIER_NONE/- text/html
1476776489.725      0 ... TAG_NONE/501 4079 GET https://dl.itch.ovh/isolate/windows-386/LATEST? - HIER_NONE/- text/html
1476776489.725      0 ... TAG_NONE/501 4076 GET https://dl.itch.ovh/butler/windows-386/LATEST? - HIER_NONE/- text/html
1476776490.479      0 ... TAG_NONE/501 4033 GET https://locales.itch.ovh/itch/en.json? - HIER_NONE/- text/html

Now, that's not how things are supposed to go at all.

For proxied https URIs, the app should connect to the proxy and use the CONNECT method to request that the proxy connect to the remote server. Once it has done that, it should then be able to use that connection as if it were directly connected to the remote server and directly requesting URIs. What goes on inside that connection is opaque to the proxy, which just shovels bits back and forth.

Addendum: It isn't so very different to going direct, except that your connection to the server is established with an extra step.

Second addendum: I could have explained that better. It's late. Let me take another run up at it.
For https URIs, instead of connecting to _host:port_ (the server) and making your request, instead you:
1. Connect to proxyhost:proxyport
2. Request the connection like:
   CONNECT _host:port_ HTTP/1.1
   Host: _hostname_
   Proxy-Connection: Keep-Alive
3. Proceed as you would have to request the object.

**Comment by fasterthanlime** [comment]
That definitely looks like [tunnel-agent](https://github.com/request/tunnel-agent/blob/master/index.js) is doing, I'll look into that and test with Squid. Thanks for the additional info!

**Comment by DancerV** [comment]
Tried it with polipo as a proxy as well, which also choked, just FYI.

**Comment by fasterthanlime** [comment]
Good news, it looks like https://github.com/electron/electron/pull/7577 might be exactly what we need.

**Comment by DancerV** [comment]
That looks ideal, from what I can see!
