### ISSUE TITLE
For .jar, check for java presence, tell user to install if not there

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#945]
see https://github.com/itchio/itch-compatibility-watchlist/issues/215

**Comment by mayuso** [comment]
As an amateur developer who only uses LibGDX for now. This sounds really good. 

I have never had any complains on my games regarding java instalation (Mainly because I have 3 downloads total, and I am sure all 3 are mine), but having this feature might help other, and even me in the future if I start making better games and people start dowloading them.

**Comment by ESWAT** [comment]
When should we tell the user about the java dependency if it’s not installed? When first downloading, installing or launching?

**Comment by fasterthanlime** [comment]
> When should we tell the user about the java dependency if it’s not installed? When first downloading, installing or launching?

I think when launching is the best time to do it.
- We don't know yet at download time, since a .jar might be hiding in a .zip
- Doing it at install time would make mass-install ("Install all games" from collection, a feature I've had in mind for a while)
